In [1]:
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("mission_launches.csv")

In [3]:
df

,Unnamed: 0.1,Unnamed: 0,Organisation,Location,Date,Detail,Rocket_Status,Price,Mission_Status
0,0,0,SpaceX,"LC-39A, Kennedy Space Center, Florida, USA","Fri Aug 07, 2020 05:12 UTC",Falcon 9 Block 5 | Starlink V1 L9 & BlackSky,StatusActive,50.0,Success
1,1,1,CASC,"Site 9401 (SLS-2), Jiuquan Satellite Launch Ce...","Thu Aug 06, 2020 04:01 UTC",Long March 2D | Gaofen-9 04 & Q-SAT,StatusActive,29.75,Success
2,2,2,SpaceX,"Pad A, Boca Chica, Texas, USA","Tue Aug 04, 2020 23:57 UTC",Starship Prototype | 150 Meter Hop,StatusActive,NaN,Success
3,3,3,Roscosmos,"Site 200/39, Baikonur Cosmodrome, Kazakhstan","Thu Jul 30, 2020 21:25 UTC",Proton-M/Briz-M | Ekspress-80 & Ekspress-103,StatusActive,65.0,Success
4,4,4,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA","Thu Jul 30, 2020 11:50 UTC",Atlas V 541 | Perseverance,StatusActive,145.0,Success
...,...,...,...,...,...,...,...,...,...
4319,4319,4319,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA","Wed Feb 05, 1958 07:33 UTC",Vanguard | Vanguard TV3BU,StatusRetired,NaN,Failure
4320,4320,4320,AMBA,"LC-26A, Cape Canaveral AFS, Florida, USA","Sat Feb 01, 1958 03:48 UTC",Juno I | Explorer 1,StatusRetired,NaN,Success
4321,4321,4321,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA","Fri Dec 06, 1957 16:44 UTC",Vanguard | Vanguard TV3,StatusRetired,NaN,Failure
4322,4322,4322,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan","Sun Nov 03, 1957 02:30 UTC",Sputnik 8K71PS | Sputnik-2,StatusRetired,NaN,Success
4323,4323,4323,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan","Fri Oct 04, 1957 19:28 UTC",Sputnik 8K71PS | Sputnik-1,StatusRetired,NaN,Success

In [4]:
df.shape

(4324, 9)

In [5]:
df.dtypes

Unnamed: 0.1       int64
Unnamed: 0         int64
Organisation      object
Location          object
Date              object
Detail            object
Rocket_Status     object
Price             object
Mission_Status    object
dtype: object

In [6]:
df.dtypes

Unnamed: 0.1       int64
Unnamed: 0         int64
Organisation      object
Location          object
Date              object
Detail            object
Rocket_Status     object
Price             object
Mission_Status    object
dtype: object

In [7]:
df

,Unnamed: 0.1,Unnamed: 0,Organisation,Location,Date,Detail,Rocket_Status,Price,Mission_Status
0,0,0,SpaceX,"LC-39A, Kennedy Space Center, Florida, USA","Fri Aug 07, 2020 05:12 UTC",Falcon 9 Block 5 | Starlink V1 L9 & BlackSky,StatusActive,50.0,Success
1,1,1,CASC,"Site 9401 (SLS-2), Jiuquan Satellite Launch Ce...","Thu Aug 06, 2020 04:01 UTC",Long March 2D | Gaofen-9 04 & Q-SAT,StatusActive,29.75,Success
2,2,2,SpaceX,"Pad A, Boca Chica, Texas, USA","Tue Aug 04, 2020 23:57 UTC",Starship Prototype | 150 Meter Hop,StatusActive,NaN,Success
3,3,3,Roscosmos,"Site 200/39, Baikonur Cosmodrome, Kazakhstan","Thu Jul 30, 2020 21:25 UTC",Proton-M/Briz-M | Ekspress-80 & Ekspress-103,StatusActive,65.0,Success
4,4,4,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA","Thu Jul 30, 2020 11:50 UTC",Atlas V 541 | Perseverance,StatusActive,145.0,Success
...,...,...,...,...,...,...,...,...,...
4319,4319,4319,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA","Wed Feb 05, 1958 07:33 UTC",Vanguard | Vanguard TV3BU,StatusRetired,NaN,Failure
4320,4320,4320,AMBA,"LC-26A, Cape Canaveral AFS, Florida, USA","Sat Feb 01, 1958 03:48 UTC",Juno I | Explorer 1,StatusRetired,NaN,Success
4321,4321,4321,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA","Fri Dec 06, 1957 16:44 UTC",Vanguard | Vanguard TV3,StatusRetired,NaN,Failure
4322,4322,4322,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan","Sun Nov 03, 1957 02:30 UTC",Sputnik 8K71PS | Sputnik-2,StatusRetired,NaN,Success
4323,4323,4323,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan","Fri Oct 04, 1957 19:28 UTC",Sputnik 8K71PS | Sputnik-1,StatusRetired,NaN,Success

In [8]:
df.dtypes

Unnamed: 0.1       int64
Unnamed: 0         int64
Organisation      object
Location          object
Date              object
Detail            object
Rocket_Status     object
Price             object
Mission_Status    object
dtype: object

In [9]:
df['Date'] = pd.to_datetime(df['Date'], format='mixed')

/tmp/ipykernel_3058/1908289283.py:1: FutureWarning: In a future version of pandas, parsing datetimes with mixed time zones will raise an error unless `utc=True`. Please specify `utc=True` to opt in to the new behaviour and silence this warning. To create a `Series` with mixed offsets and `object` dtype, please use `apply` and `datetime.datetime.strptime`
  df['Date'] = pd.to_datetime(df['Date'], format='mixed')

In [10]:
df

,Unnamed: 0.1,Unnamed: 0,Organisation,Location,Date,Detail,Rocket_Status,Price,Mission_Status
0,0,0,SpaceX,"LC-39A, Kennedy Space Center, Florida, USA",2020-08-07 05:12:00+00:00,Falcon 9 Block 5 | Starlink V1 L9 & BlackSky,StatusActive,50.0,Success
1,1,1,CASC,"Site 9401 (SLS-2), Jiuquan Satellite Launch Ce...",2020-08-06 04:01:00+00:00,Long March 2D | Gaofen-9 04 & Q-SAT,StatusActive,29.75,Success
2,2,2,SpaceX,"Pad A, Boca Chica, Texas, USA",2020-08-04 23:57:00+00:00,Starship Prototype | 150 Meter Hop,StatusActive,NaN,Success
3,3,3,Roscosmos,"Site 200/39, Baikonur Cosmodrome, Kazakhstan",2020-07-30 21:25:00+00:00,Proton-M/Briz-M | Ekspress-80 & Ekspress-103,StatusActive,65.0,Success
4,4,4,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA",2020-07-30 11:50:00+00:00,Atlas V 541 | Perseverance,StatusActive,145.0,Success
...,...,...,...,...,...,...,...,...,...
4319,4319,4319,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1958-02-05 07:33:00+00:00,Vanguard | Vanguard TV3BU,StatusRetired,NaN,Failure
4320,4320,4320,AMBA,"LC-26A, Cape Canaveral AFS, Florida, USA",1958-02-01 03:48:00+00:00,Juno I | Explorer 1,StatusRetired,NaN,Success
4321,4321,4321,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1957-12-06 16:44:00+00:00,Vanguard | Vanguard TV3,StatusRetired,NaN,Failure
4322,4322,4322,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-11-03 02:30:00+00:00,Sputnik 8K71PS | Sputnik-2,StatusRetired,NaN,Success
4323,4323,4323,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-10-04 19:28:00+00:00,Sputnik 8K71PS | Sputnik-1,StatusRetired,NaN,Success

In [11]:
df['Price'] = df['Price'].str.replace(',',"").astype(float)

In [12]:
df['Date'] = pd.to_datetime(df['Date'], format='mixed', utc=True)
df['year'] = df['Date'].dt.year

In [13]:
df

,Unnamed: 0.1,Unnamed: 0,Organisation,Location,Date,Detail,Rocket_Status,Price,Mission_Status,year
0,0,0,SpaceX,"LC-39A, Kennedy Space Center, Florida, USA",2020-08-07 05:12:00+00:00,Falcon 9 Block 5 | Starlink V1 L9 & BlackSky,StatusActive,50.00,Success,2020
1,1,1,CASC,"Site 9401 (SLS-2), Jiuquan Satellite Launch Ce...",2020-08-06 04:01:00+00:00,Long March 2D | Gaofen-9 04 & Q-SAT,StatusActive,29.75,Success,2020
2,2,2,SpaceX,"Pad A, Boca Chica, Texas, USA",2020-08-04 23:57:00+00:00,Starship Prototype | 150 Meter Hop,StatusActive,NaN,Success,2020
3,3,3,Roscosmos,"Site 200/39, Baikonur Cosmodrome, Kazakhstan",2020-07-30 21:25:00+00:00,Proton-M/Briz-M | Ekspress-80 & Ekspress-103,StatusActive,65.00,Success,2020
4,4,4,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA",2020-07-30 11:50:00+00:00,Atlas V 541 | Perseverance,StatusActive,145.00,Success,2020
...,...,...,...,...,...,...,...,...,...,...
4319,4319,4319,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1958-02-05 07:33:00+00:00,Vanguard | Vanguard TV3BU,StatusRetired,NaN,Failure,1958
4320,4320,4320,AMBA,"LC-26A, Cape Canaveral AFS, Florida, USA",1958-02-01 03:48:00+00:00,Juno I | Explorer 1,StatusRetired,NaN,Success,1958
4321,4321,4321,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1957-12-06 16:44:00+00:00,Vanguard | Vanguard TV3,StatusRetired,NaN,Failure,1957
4322,4322,4322,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-11-03 02:30:00+00:00,Sputnik 8K71PS | Sputnik-2,StatusRetired,NaN,Success,1957
4323,4323,4323,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-10-04 19:28:00+00:00,Sputnik 8K71PS | Sputnik-1,StatusRetired,NaN,Success,1957

In [14]:
df['Date'] = pd.to_datetime(df['Date'], format='mixed', utc=True)
df['year'] = df['Date'].dt.year
df_yearly_attempts = df.groupby('year').agg({'year':pd.Series.count})
df_yearly_attempts.columns = ['no. of attempts']
df_yearly_attempts

      no. of attempts
year
1957                3
1958               28
1959               20
1960               39
1961               52
...               ...
2016               90
2017               92
2018              117
2019              109
2020               63

[64 rows x 1 columns]

In [15]:
df_success_missions = df[df['Mission_Status'] == 'Success']
successful_missions = df_success_missions.groupby('year').agg({'year':pd.Series.count})

In [16]:
organisation_successful = df_success_missions.groupby('Organisation').agg({'Organisation':pd.Series.count})

In [17]:
organisation_successful.columns = ['success_count']

In [18]:
organisation_successful

                  success_count
Organisation
AMBA                          4
ASI                           9
Arianespace                 269
Arm??e de l'Air               3
Blue Origin                  12
Boeing                      131
CASC                        231
CASIC                         3
CECLES                        1
CNES                          6
Douglas                       1
ESA                           9
Eurockot                     12
ExPace                        9
General Dynamics            203
IAI                           9
ILS                          45
IRGC                          1
ISA                           4
ISAS                         26
ISRO                         63
JAXA                          6
KARI                          1
KCST                          2
Khrunichev                    1
Kosmotras                    21
Land Launch                   6
Lockheed                     74
MHI                          80
MITT                          6
Martin Marietta             100
NASA                        186
Northrop                     74
OKB-586                       2
RAE                           1
RVSN USSR                  1614
Rocket Lab                   11
Roscosmos                    51
SRC                           2
Sea Launch                   33
SpaceX                       94
Starsem                       1
ULA                         139
US Air Force                129
US Navy                       2
UT                            1
VKS RF                      188
Yuzhmash                      2
i-Space                       1

In [19]:
organisation_successful.sort_values(by='success_count',ascending=False,inplace=True)

In [20]:
organisation_successful

                  success_count
Organisation
RVSN USSR                  1614
Arianespace                 269
CASC                        231
General Dynamics            203
VKS RF                      188
NASA                        186
ULA                         139
Boeing                      131
US Air Force                129
Martin Marietta             100
SpaceX                       94
MHI                          80
Northrop                     74
Lockheed                     74
ISRO                         63
Roscosmos                    51
ILS                          45
Sea Launch                   33
ISAS                         26
Kosmotras                    21
Blue Origin                  12
Eurockot                     12
Rocket Lab                   11
ASI                           9
ExPace                        9
IAI                           9
ESA                           9
JAXA                          6
MITT                          6
Land Launch                   6
CNES                          6
AMBA                          4
ISA                           4
CASIC                         3
Arm??e de l'Air               3
US Navy                       2
SRC                           2
Yuzhmash                      2
KCST                          2
OKB-586                       2
CECLES                        1
Douglas                       1
KARI                          1
Khrunichev                    1
IRGC                          1
RAE                           1
Starsem                       1
UT                            1
i-Space                       1

In [21]:
successful_missions

      year
year
1957     2
1958     6
1959     8
1960    19
1961    32
...    ...
2016    86
2017    84
2018   113
2019   100
2020    57

[64 rows x 1 columns]

In [22]:
successful_missions.columns=['no. of successful missions']

In [23]:
highest_no_of_successful_missions = successful_missions['no. of successful missions'].idxmax()
successful_missions.loc[highest_no_of_successful_missions]

no. of successful missions    113
Name: 2018, dtype: int64

In [24]:
df_failure_missions = df[df['Mission_Status'] == 'Failure']
failed_missions = df_failure_missions.groupby('year').agg({'year':pd.Series.count})
failed_missions.columns=['no. of failed missions']
highest_no_of_missions_failed = failed_missions['no. of failed missions'].idxmax()
failed_missions.loc[highest_no_of_missions_failed]

no. of failed missions    20
Name: 1958, dtype: int64

In [25]:
organisation_successful.head()

                  success_count
Organisation
RVSN USSR                  1614
Arianespace                 269
CASC                        231
General Dynamics            203
VKS RF                      188

In [26]:
bar_graph = px.bar(organisation_successful.head(), x=organisation_successful.head().index, y='success_count', title='top 5 most successful organsiations')
bar_graph.update_layout(xaxis_title='Organsation',yaxis_title='Number of successful operations')
bar_graph.show()

In [27]:
df_most_failed_organisations = df[df['Mission_Status'] == 'Failure']
most_failed_organisations = df_most_failed_organisations.groupby('Organisation').agg({'Organisation':pd.Series.count})
most_failed_organisations.columns = ['no. of failed missions']
failure_tally = most_failed_organisations.sort_values(by='no. of failed missions', ascending=False)
failure_tally

                  no. of failed missions
Organisation
RVSN USSR                            121
General Dynamics                      37
US Air Force                          30
US Navy                               14
CASC                                  14
Martin Marietta                       11
NASA                                  11
ISA                                    8
ISRO                                   8
Arianespace                            7
VKS RF                                 7
Northrop                               7
Lockheed                               5
UT                                     4
SpaceX                                 4
Sea Launch                             3
ESA                                    3
Boeing                                 3
CECLES                                 3
AMBA                                   3
KCST                                   3
ISAS                                   3
Roscosmos                              3
AEB                                    2
IAI                                    2
CNES                                   2
CASIC                                  2
KARI                                   2
MHI                                    2
Rocket Lab                             2
EER                                    1
Eurockot                               1
Exos                                   1
ExPace                                 1
JAXA                                   1
MITT                                   1
Landspace                              1
Kosmotras                              1
OneSpace                               1
SRC                                    1
RAE                                    1
Sandia                                 1
Virgin Orbit                           1

In [28]:
succes_failure_df = pd.merge(organisation_successful, failure_tally, on='Organisation', how='left')
failed_to_success_ratio = succes_failure_df['no. of failed missions']/succes_failure_df['success_count']
succes_failure_df['failed_to_success_ratio'] = failed_to_success_ratio
success_failure_df_sorted = succes_failure_df.sort_values(by='failed_to_success_ratio', ascending=True)

In [29]:
success_failure_df_top5 = success_failure_df_sorted.head()

In [30]:
success_failure_df_top5

              success_count  no. of failed missions  failed_to_success_ratio
Organisation
Boeing                  131                     3.0                 0.022901
MHI                      80                     2.0                 0.025000
Arianespace             269                     7.0                 0.026022
VKS RF                  188                     7.0                 0.037234
SpaceX                   94                     4.0                 0.042553

In [31]:
sub_plots = px.bar(success_failure_df_top5, x=success_failure_df_top5.index, y=['success_count','no. of failed missions'], title='Comparison of successs as well as failed missions', barmode='group')
sub_plots.show()

In [32]:
df

,Unnamed: 0.1,Unnamed: 0,Organisation,Location,Date,Detail,Rocket_Status,Price,Mission_Status,year
0,0,0,SpaceX,"LC-39A, Kennedy Space Center, Florida, USA",2020-08-07 05:12:00+00:00,Falcon 9 Block 5 | Starlink V1 L9 & BlackSky,StatusActive,50.00,Success,2020
1,1,1,CASC,"Site 9401 (SLS-2), Jiuquan Satellite Launch Ce...",2020-08-06 04:01:00+00:00,Long March 2D | Gaofen-9 04 & Q-SAT,StatusActive,29.75,Success,2020
2,2,2,SpaceX,"Pad A, Boca Chica, Texas, USA",2020-08-04 23:57:00+00:00,Starship Prototype | 150 Meter Hop,StatusActive,NaN,Success,2020
3,3,3,Roscosmos,"Site 200/39, Baikonur Cosmodrome, Kazakhstan",2020-07-30 21:25:00+00:00,Proton-M/Briz-M | Ekspress-80 & Ekspress-103,StatusActive,65.00,Success,2020
4,4,4,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA",2020-07-30 11:50:00+00:00,Atlas V 541 | Perseverance,StatusActive,145.00,Success,2020
...,...,...,...,...,...,...,...,...,...,...
4319,4319,4319,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1958-02-05 07:33:00+00:00,Vanguard | Vanguard TV3BU,StatusRetired,NaN,Failure,1958
4320,4320,4320,AMBA,"LC-26A, Cape Canaveral AFS, Florida, USA",1958-02-01 03:48:00+00:00,Juno I | Explorer 1,StatusRetired,NaN,Success,1958
4321,4321,4321,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1957-12-06 16:44:00+00:00,Vanguard | Vanguard TV3,StatusRetired,NaN,Failure,1957
4322,4322,4322,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-11-03 02:30:00+00:00,Sputnik 8K71PS | Sputnik-2,StatusRetired,NaN,Success,1957
4323,4323,4323,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-10-04 19:28:00+00:00,Sputnik 8K71PS | Sputnik-1,StatusRetired,NaN,Success,1957

In [33]:
success_count = df[df['Mission_Status'] == 'Success']

In [34]:
success_count

,Unnamed: 0.1,Unnamed: 0,Organisation,Location,Date,Detail,Rocket_Status,Price,Mission_Status,year
0,0,0,SpaceX,"LC-39A, Kennedy Space Center, Florida, USA",2020-08-07 05:12:00+00:00,Falcon 9 Block 5 | Starlink V1 L9 & BlackSky,StatusActive,50.00,Success,2020
1,1,1,CASC,"Site 9401 (SLS-2), Jiuquan Satellite Launch Ce...",2020-08-06 04:01:00+00:00,Long March 2D | Gaofen-9 04 & Q-SAT,StatusActive,29.75,Success,2020
2,2,2,SpaceX,"Pad A, Boca Chica, Texas, USA",2020-08-04 23:57:00+00:00,Starship Prototype | 150 Meter Hop,StatusActive,NaN,Success,2020
3,3,3,Roscosmos,"Site 200/39, Baikonur Cosmodrome, Kazakhstan",2020-07-30 21:25:00+00:00,Proton-M/Briz-M | Ekspress-80 & Ekspress-103,StatusActive,65.00,Success,2020
4,4,4,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA",2020-07-30 11:50:00+00:00,Atlas V 541 | Perseverance,StatusActive,145.00,Success,2020
...,...,...,...,...,...,...,...,...,...,...
4316,4316,4316,AMBA,"LC-5, Cape Canaveral AFS, Florida, USA",1958-03-26 17:38:00+00:00,Juno I | Explorer 3,StatusRetired,NaN,Success,1958
4317,4317,4317,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1958-03-17 12:15:00+00:00,Vanguard | Vanguard 1,StatusRetired,NaN,Success,1958
4320,4320,4320,AMBA,"LC-26A, Cape Canaveral AFS, Florida, USA",1958-02-01 03:48:00+00:00,Juno I | Explorer 1,StatusRetired,NaN,Success,1958
4322,4322,4322,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-11-03 02:30:00+00:00,Sputnik 8K71PS | Sputnik-2,StatusRetired,NaN,Success,1957
4323,4323,4323,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-10-04 19:28:00+00:00,Sputnik 8K71PS | Sputnik-1,StatusRetired,NaN,Success,1957

In [35]:
succuessful_orgs_that_year = success_count.groupby('year')['Organisation'].agg(lambda x:x.value_counts().idxmax())

In [36]:
succuessful_orgs_that_year_count = success_count.groupby('year')['Organisation'].agg(lambda x:x.value_counts().max())

In [37]:
succuessful_orgs_that_year_count

year
1957     2
1958     3
1959     5
1960    14
1961    17
        ..
2016    20
2017    18
2018    37
2019    26
2020    17
Name: Organisation, Length: 64, dtype: int64

In [38]:
succuessful_orgs_that_year

year
1957       RVSN USSR
1958            AMBA
1959    US Air Force
1960    US Air Force
1961    US Air Force
            ...
2016            CASC
2017          SpaceX
2018            CASC
2019            CASC
2020            CASC
Name: Organisation, Length: 64, dtype: object

In [39]:
df_most_successful_orgs_everyYear = pd.merge(succuessful_orgs_that_year, succuessful_orgs_that_year_count, on='year', how='left')
df_most_successful_orgs_everyYear

     Organisation_x  Organisation_y
year
1957      RVSN USSR               2
1958           AMBA               3
1959   US Air Force               5
1960   US Air Force              14
1961   US Air Force              17
...             ...             ...
2016           CASC              20
2017         SpaceX              18
2018           CASC              37
2019           CASC              26
2020           CASC              17

[64 rows x 2 columns]

In [40]:
df_most_successful_orgs_everyYear_last5_years = df_most_successful_orgs_everyYear.tail()

In [41]:
df_most_successful_orgs_everyYear_last5_years

     Organisation_x  Organisation_y
year
2016           CASC              20
2017         SpaceX              18
2018           CASC              37
2019           CASC              26
2020           CASC              17

In [42]:
bar_graph2 = px.bar(df_most_successful_orgs_everyYear_last5_years, x=df_most_successful_orgs_everyYear_last5_years.index, y='Organisation_y', title='successful organisations of past 5 years', color='Organisation_x')

In [43]:
bar_graph2.show()

In [44]:
df

,Unnamed: 0.1,Unnamed: 0,Organisation,Location,Date,Detail,Rocket_Status,Price,Mission_Status,year
0,0,0,SpaceX,"LC-39A, Kennedy Space Center, Florida, USA",2020-08-07 05:12:00+00:00,Falcon 9 Block 5 | Starlink V1 L9 & BlackSky,StatusActive,50.00,Success,2020
1,1,1,CASC,"Site 9401 (SLS-2), Jiuquan Satellite Launch Ce...",2020-08-06 04:01:00+00:00,Long March 2D | Gaofen-9 04 & Q-SAT,StatusActive,29.75,Success,2020
2,2,2,SpaceX,"Pad A, Boca Chica, Texas, USA",2020-08-04 23:57:00+00:00,Starship Prototype | 150 Meter Hop,StatusActive,NaN,Success,2020
3,3,3,Roscosmos,"Site 200/39, Baikonur Cosmodrome, Kazakhstan",2020-07-30 21:25:00+00:00,Proton-M/Briz-M | Ekspress-80 & Ekspress-103,StatusActive,65.00,Success,2020
4,4,4,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA",2020-07-30 11:50:00+00:00,Atlas V 541 | Perseverance,StatusActive,145.00,Success,2020
...,...,...,...,...,...,...,...,...,...,...
4319,4319,4319,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1958-02-05 07:33:00+00:00,Vanguard | Vanguard TV3BU,StatusRetired,NaN,Failure,1958
4320,4320,4320,AMBA,"LC-26A, Cape Canaveral AFS, Florida, USA",1958-02-01 03:48:00+00:00,Juno I | Explorer 1,StatusRetired,NaN,Success,1958
4321,4321,4321,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1957-12-06 16:44:00+00:00,Vanguard | Vanguard TV3,StatusRetired,NaN,Failure,1957
4322,4322,4322,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-11-03 02:30:00+00:00,Sputnik 8K71PS | Sputnik-2,StatusRetired,NaN,Success,1957
4323,4323,4323,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-10-04 19:28:00+00:00,Sputnik 8K71PS | Sputnik-1,StatusRetired,NaN,Success,1957

In [45]:
active_ones = df[df['Rocket_Status'] == 'StatusActive']

In [46]:
longest_active = active_ones['year'].idxmin()

In [47]:
active_ones.loc[longest_active]

Unnamed: 0.1                                                   2309
Unnamed: 0                                                     2309
Organisation                                                   CASC
Location          Site 138 (LA-2B), Jiuquan Satellite Launch Cen...
Date                                      1982-09-09 07:19:00+00:00
Detail                                   Long March 2C | FSW-0 No.4
Rocket_Status                                          StatusActive
Price                                                          30.8
Mission_Status                                              Success
year                                                           1982
Name: 2309, dtype: object

In [48]:
max_kharcha = df['Price'].idxmax()
df.loc[max_kharcha]

Unnamed: 0.1                                              1916
Unnamed: 0                                                1916
Organisation                                         RVSN USSR
Location          Site 110/37, Baikonur Cosmodrome, Kazakhstan
Date                                 1988-11-15 03:00:00+00:00
Detail                                  Energiya/Buran | Buran
Rocket_Status                                    StatusRetired
Price                                                   5000.0
Mission_Status                                         Success
year                                                      1988
Name: 1916, dtype: object

In [49]:
min_kharcha = df['Price'].idxmin()
df.loc[min_kharcha]

Unnamed: 0.1                                          26
Unnamed: 0                                            26
Organisation                                        CASC
Location          Xichang Satellite Launch Center, China
Date                           2020-05-29 20:13:00+00:00
Detail                   Long March 11 | XJS-G and XJS-H
Rocket_Status                               StatusActive
Price                                                5.3
Mission_Status                                   Success
year                                                2020
Name: 26, dtype: object

In [50]:
active_ones

,Unnamed: 0.1,Unnamed: 0,Organisation,Location,Date,Detail,Rocket_Status,Price,Mission_Status,year
0,0,0,SpaceX,"LC-39A, Kennedy Space Center, Florida, USA",2020-08-07 05:12:00+00:00,Falcon 9 Block 5 | Starlink V1 L9 & BlackSky,StatusActive,50.00,Success,2020
1,1,1,CASC,"Site 9401 (SLS-2), Jiuquan Satellite Launch Ce...",2020-08-06 04:01:00+00:00,Long March 2D | Gaofen-9 04 & Q-SAT,StatusActive,29.75,Success,2020
2,2,2,SpaceX,"Pad A, Boca Chica, Texas, USA",2020-08-04 23:57:00+00:00,Starship Prototype | 150 Meter Hop,StatusActive,NaN,Success,2020
3,3,3,Roscosmos,"Site 200/39, Baikonur Cosmodrome, Kazakhstan",2020-07-30 21:25:00+00:00,Proton-M/Briz-M | Ekspress-80 & Ekspress-103,StatusActive,65.00,Success,2020
4,4,4,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA",2020-07-30 11:50:00+00:00,Atlas V 541 | Perseverance,StatusActive,145.00,Success,2020
...,...,...,...,...,...,...,...,...,...,...
2041,2041,2041,CASC,"Site 138 (LA-2B), Jiuquan Satellite Launch Cen...",1986-10-06 05:40:00+00:00,Long March 2C | FSW-0 No.8,StatusActive,30.80,Success,1986
2101,2101,2101,CASC,"Site 138 (LA-2B), Jiuquan Satellite Launch Cen...",1985-10-21 05:04:00+00:00,Long March 2C | FSW-0 No.7,StatusActive,30.80,Success,1985
2177,2177,2177,CASC,"Site 138 (LA-2B), Jiuquan Satellite Launch Cen...",1984-09-12 05:44:00+00:00,Long March 2C | FSW-0 No.6,StatusActive,30.80,Success,1984
2249,2249,2249,CASC,"Site 138 (LA-2B), Jiuquan Satellite Launch Cen...",1983-08-19 06:00:00+00:00,Long March 2C | FSW-0 No.5,StatusActive,30.80,Success,1983
2309,2309,2309,CASC,"Site 138 (LA-2B), Jiuquan Satellite Launch Cen...",1982-09-09 07:19:00+00:00,Long March 2C | FSW-0 No.4,StatusActive,30.80,Success,1982

In [51]:
cost_df = df.groupby('Organisation').agg({'Price':pd.Series.sum})

In [52]:
cost_df.columns = ['total_cost']

In [53]:
cost_df.sort_values(by='total_cost', ascending=False, inplace=True)

In [54]:

cost_df_top5 = cost_df.head()

In [55]:
cost_df_top5

              total_cost
Organisation
NASA            76280.00
Arianespace     16345.00
ULA             14798.00
RVSN USSR       10000.00
CASC             6340.26

In [56]:
bar_graph3 = px.bar(cost_df_top5, x=cost_df_top5.index, y='total_cost',title="heavy budget organisations", color=cost_df_top5.index)

In [57]:
bar_graph3

In [58]:
bar_graph4 = px.bar(df_most_successful_orgs_everyYear.tail(), x=df_most_successful_orgs_everyYear.tail().index, y='Organisation_y', title='successful organisations of past 5 years', color='Organisation_x')

In [59]:
df_most_successful_orgs_everyYear.tail()

     Organisation_x  Organisation_y
year
2016           CASC              20
2017         SpaceX              18
2018           CASC              37
2019           CASC              26
2020           CASC              17

In [60]:
bar_graph4.show()

In [61]:
df

,Unnamed: 0.1,Unnamed: 0,Organisation,Location,Date,Detail,Rocket_Status,Price,Mission_Status,year
0,0,0,SpaceX,"LC-39A, Kennedy Space Center, Florida, USA",2020-08-07 05:12:00+00:00,Falcon 9 Block 5 | Starlink V1 L9 & BlackSky,StatusActive,50.00,Success,2020
1,1,1,CASC,"Site 9401 (SLS-2), Jiuquan Satellite Launch Ce...",2020-08-06 04:01:00+00:00,Long March 2D | Gaofen-9 04 & Q-SAT,StatusActive,29.75,Success,2020
2,2,2,SpaceX,"Pad A, Boca Chica, Texas, USA",2020-08-04 23:57:00+00:00,Starship Prototype | 150 Meter Hop,StatusActive,NaN,Success,2020
3,3,3,Roscosmos,"Site 200/39, Baikonur Cosmodrome, Kazakhstan",2020-07-30 21:25:00+00:00,Proton-M/Briz-M | Ekspress-80 & Ekspress-103,StatusActive,65.00,Success,2020
4,4,4,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA",2020-07-30 11:50:00+00:00,Atlas V 541 | Perseverance,StatusActive,145.00,Success,2020
...,...,...,...,...,...,...,...,...,...,...
4319,4319,4319,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1958-02-05 07:33:00+00:00,Vanguard | Vanguard TV3BU,StatusRetired,NaN,Failure,1958
4320,4320,4320,AMBA,"LC-26A, Cape Canaveral AFS, Florida, USA",1958-02-01 03:48:00+00:00,Juno I | Explorer 1,StatusRetired,NaN,Success,1958
4321,4321,4321,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1957-12-06 16:44:00+00:00,Vanguard | Vanguard TV3,StatusRetired,NaN,Failure,1957
4322,4322,4322,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-11-03 02:30:00+00:00,Sputnik 8K71PS | Sputnik-2,StatusRetired,NaN,Success,1957
4323,4323,4323,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-10-04 19:28:00+00:00,Sputnik 8K71PS | Sputnik-1,StatusRetired,NaN,Success,1957

In [62]:
cost_df

                  total_cost
Organisation
NASA                76280.00
Arianespace         16345.00
ULA                 14798.00
RVSN USSR           10000.00
CASC                 6340.26
SpaceX               5444.00
Northrop             3930.00
MHI                  3532.50
ISRO                 2177.00
US Air Force         1550.92
VKS RF               1548.90
ILS                  1320.00
Boeing               1241.00
Roscosmos            1187.50
Martin Marietta       721.40
Kosmotras             638.00
Eurockot              543.40
Lockheed              280.00
JAXA                  168.00
Rocket Lab             97.50
ESA                    37.00
ExPace                 28.30
EER                    20.00
Sandia                 15.00
Virgin Orbit           12.00
ISAS                    0.00
IRGC                    0.00
ISA                     0.00
Exos                    0.00
General Dynamics        0.00
CECLES                  0.00
IAI                     0.00
CNES                    0.00
Douglas                 0.00
Blue Origin             0.00
AEB                     0.00
ASI                     0.00
AMBA                    0.00
Arm??e de l'Air         0.00
CASIC                   0.00
RAE                     0.00
OneSpace                0.00
OKB-586                 0.00
MITT                    0.00
Khrunichev              0.00
KCST                    0.00
Land Launch             0.00
Landspace               0.00
KARI                    0.00
Starsem                 0.00
SRC                     0.00
Sea Launch              0.00
UT                      0.00
US Navy                 0.00
Yuzhmash                0.00
i-Space                 0.00

In [63]:
success_count

,Unnamed: 0.1,Unnamed: 0,Organisation,Location,Date,Detail,Rocket_Status,Price,Mission_Status,year
0,0,0,SpaceX,"LC-39A, Kennedy Space Center, Florida, USA",2020-08-07 05:12:00+00:00,Falcon 9 Block 5 | Starlink V1 L9 & BlackSky,StatusActive,50.00,Success,2020
1,1,1,CASC,"Site 9401 (SLS-2), Jiuquan Satellite Launch Ce...",2020-08-06 04:01:00+00:00,Long March 2D | Gaofen-9 04 & Q-SAT,StatusActive,29.75,Success,2020
2,2,2,SpaceX,"Pad A, Boca Chica, Texas, USA",2020-08-04 23:57:00+00:00,Starship Prototype | 150 Meter Hop,StatusActive,NaN,Success,2020
3,3,3,Roscosmos,"Site 200/39, Baikonur Cosmodrome, Kazakhstan",2020-07-30 21:25:00+00:00,Proton-M/Briz-M | Ekspress-80 & Ekspress-103,StatusActive,65.00,Success,2020
4,4,4,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA",2020-07-30 11:50:00+00:00,Atlas V 541 | Perseverance,StatusActive,145.00,Success,2020
...,...,...,...,...,...,...,...,...,...,...
4316,4316,4316,AMBA,"LC-5, Cape Canaveral AFS, Florida, USA",1958-03-26 17:38:00+00:00,Juno I | Explorer 3,StatusRetired,NaN,Success,1958
4317,4317,4317,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1958-03-17 12:15:00+00:00,Vanguard | Vanguard 1,StatusRetired,NaN,Success,1958
4320,4320,4320,AMBA,"LC-26A, Cape Canaveral AFS, Florida, USA",1958-02-01 03:48:00+00:00,Juno I | Explorer 1,StatusRetired,NaN,Success,1958
4322,4322,4322,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-11-03 02:30:00+00:00,Sputnik 8K71PS | Sputnik-2,StatusRetired,NaN,Success,1957
4323,4323,4323,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-10-04 19:28:00+00:00,Sputnik 8K71PS | Sputnik-1,StatusRetired,NaN,Success,1957

In [64]:
total_cost_df = df.groupby('Organisation').agg({'Price':pd.Series.sum})

In [65]:
total_cost_df.sort_values(by='Price',ascending=False,inplace=True)

In [66]:
total_cost_df

                     Price
Organisation
NASA              76280.00
Arianespace       16345.00
ULA               14798.00
RVSN USSR         10000.00
CASC               6340.26
SpaceX             5444.00
Northrop           3930.00
MHI                3532.50
ISRO               2177.00
US Air Force       1550.92
VKS RF             1548.90
ILS                1320.00
Boeing             1241.00
Roscosmos          1187.50
Martin Marietta     721.40
Kosmotras           638.00
Eurockot            543.40
Lockheed            280.00
JAXA                168.00
Rocket Lab           97.50
ESA                  37.00
ExPace               28.30
EER                  20.00
Sandia               15.00
Virgin Orbit         12.00
ISAS                  0.00
IRGC                  0.00
ISA                   0.00
Exos                  0.00
General Dynamics      0.00
CECLES                0.00
IAI                   0.00
CNES                  0.00
Douglas               0.00
Blue Origin           0.00
AEB                   0.00
ASI                   0.00
AMBA                  0.00
Arm??e de l'Air       0.00
CASIC                 0.00
RAE                   0.00
OneSpace              0.00
OKB-586               0.00
MITT                  0.00
Khrunichev            0.00
KCST                  0.00
Land Launch           0.00
Landspace             0.00
KARI                  0.00
Starsem               0.00
SRC                   0.00
Sea Launch            0.00
UT                    0.00
US Navy               0.00
Yuzhmash              0.00
i-Space               0.00

In [67]:
success_cost_df = success_count.groupby('Organisation').agg({'Price':pd.Series.sum})

In [68]:
success_cost_df.sort_values(by='Price', ascending=False, inplace=True)

In [69]:
success_cost_df

                     Price
Organisation
NASA              74220.00
Arianespace       15908.00
ULA               14689.00
RVSN USSR         10000.00
CASC               6053.15
SpaceX             5245.00
MHI                3532.50
Northrop           3515.00
ISRO               1861.00
VKS RF             1400.30
US Air Force       1369.69
ILS                1320.00
Roscosmos          1139.00
Boeing              891.00
Kosmotras           609.00
Martin Marietta     549.80
Eurockot            501.60
Lockheed            280.00
JAXA                168.00
Rocket Lab           82.50
ESA                  37.00
IAI                   0.00
General Dynamics      0.00
ExPace                0.00
CECLES                0.00
ASI                   0.00
Blue Origin           0.00
AMBA                  0.00
CNES                  0.00
Douglas               0.00
Arm??e de l'Air       0.00
CASIC                 0.00
Khrunichev            0.00
MITT                  0.00
Land Launch           0.00
ISA                   0.00
IRGC                  0.00
ISAS                  0.00
KARI                  0.00
KCST                  0.00
OKB-586               0.00
Sea Launch            0.00
SRC                   0.00
RAE                   0.00
Starsem               0.00
US Navy               0.00
UT                    0.00
Yuzhmash              0.00
i-Space               0.00

In [70]:
cost_comparison_df = pd.merge(total_cost_df, success_cost_df, on='Organisation', how='left')
cost_comparison_df

                   Price_x   Price_y
Organisation
NASA              76280.00  74220.00
Arianespace       16345.00  15908.00
ULA               14798.00  14689.00
RVSN USSR         10000.00  10000.00
CASC               6340.26   6053.15
SpaceX             5444.00   5245.00
Northrop           3930.00   3515.00
MHI                3532.50   3532.50
ISRO               2177.00   1861.00
US Air Force       1550.92   1369.69
VKS RF             1548.90   1400.30
ILS                1320.00   1320.00
Boeing             1241.00    891.00
Roscosmos          1187.50   1139.00
Martin Marietta     721.40    549.80
Kosmotras           638.00    609.00
Eurockot            543.40    501.60
Lockheed            280.00    280.00
JAXA                168.00    168.00
Rocket Lab           97.50     82.50
ESA                  37.00     37.00
ExPace               28.30      0.00
EER                  20.00       NaN
Sandia               15.00       NaN
Virgin Orbit         12.00       NaN
ISAS                  0.00      0.00
IRGC                  0.00      0.00
ISA                   0.00      0.00
Exos                  0.00       NaN
General Dynamics      0.00      0.00
CECLES                0.00      0.00
IAI                   0.00      0.00
CNES                  0.00      0.00
Douglas               0.00      0.00
Blue Origin           0.00      0.00
AEB                   0.00       NaN
ASI                   0.00      0.00
AMBA                  0.00      0.00
Arm??e de l'Air       0.00      0.00
CASIC                 0.00      0.00
RAE                   0.00      0.00
OneSpace              0.00       NaN
OKB-586               0.00      0.00
MITT                  0.00      0.00
Khrunichev            0.00      0.00
KCST                  0.00      0.00
Land Launch           0.00      0.00
Landspace             0.00       NaN
KARI                  0.00      0.00
Starsem               0.00      0.00
SRC                   0.00      0.00
Sea Launch            0.00      0.00
UT                    0.00      0.00
US Navy               0.00      0.00
Yuzhmash              0.00      0.00
i-Space               0.00      0.00

In [71]:
failures_cost_df = cost_comparison_df['Price_x'] - cost_comparison_df['Price_y']

In [72]:
failures_cost_df

Organisation
NASA                2060.00
Arianespace          437.00
ULA                  109.00
RVSN USSR              0.00
CASC                 287.11
SpaceX               199.00
Northrop             415.00
MHI                    0.00
ISRO                 316.00
US Air Force         181.23
VKS RF               148.60
ILS                    0.00
Boeing               350.00
Roscosmos             48.50
Martin Marietta      171.60
Kosmotras             29.00
Eurockot              41.80
Lockheed               0.00
JAXA                   0.00
Rocket Lab            15.00
ESA                    0.00
ExPace                28.30
EER                     NaN
Sandia                  NaN
Virgin Orbit            NaN
ISAS                   0.00
IRGC                   0.00
ISA                    0.00
Exos                    NaN
General Dynamics       0.00
CECLES                 0.00
IAI                    0.00
CNES                   0.00
Douglas                0.00
Blue Origin            0.00
AEB                     NaN
ASI                    0.00
AMBA                   0.00
Arm??e de l'Air        0.00
CASIC                  0.00
RAE                    0.00
OneSpace                NaN
OKB-586                0.00
MITT                   0.00
Khrunichev             0.00
KCST                   0.00
Land Launch            0.00
Landspace               NaN
KARI                   0.00
Starsem                0.00
SRC                    0.00
Sea Launch             0.00
UT                     0.00
US Navy                0.00
Yuzhmash               0.00
i-Space                0.00
dtype: float64

In [73]:
cost_comparison_df['cost_of_failures'] = failures_cost_df

In [74]:
cost_comparison_df

                   Price_x   Price_y  cost_of_failures
Organisation
NASA              76280.00  74220.00           2060.00
Arianespace       16345.00  15908.00            437.00
ULA               14798.00  14689.00            109.00
RVSN USSR         10000.00  10000.00              0.00
CASC               6340.26   6053.15            287.11
SpaceX             5444.00   5245.00            199.00
Northrop           3930.00   3515.00            415.00
MHI                3532.50   3532.50              0.00
ISRO               2177.00   1861.00            316.00
US Air Force       1550.92   1369.69            181.23
VKS RF             1548.90   1400.30            148.60
ILS                1320.00   1320.00              0.00
Boeing             1241.00    891.00            350.00
Roscosmos          1187.50   1139.00             48.50
Martin Marietta     721.40    549.80            171.60
Kosmotras           638.00    609.00             29.00
Eurockot            543.40    501.60             41.80
Lockheed            280.00    280.00              0.00
JAXA                168.00    168.00              0.00
Rocket Lab           97.50     82.50             15.00
ESA                  37.00     37.00              0.00
ExPace               28.30      0.00             28.30
EER                  20.00       NaN               NaN
Sandia               15.00       NaN               NaN
Virgin Orbit         12.00       NaN               NaN
ISAS                  0.00      0.00              0.00
IRGC                  0.00      0.00              0.00
ISA                   0.00      0.00              0.00
Exos                  0.00       NaN               NaN
General Dynamics      0.00      0.00              0.00
CECLES                0.00      0.00              0.00
IAI                   0.00      0.00              0.00
CNES                  0.00      0.00              0.00
Douglas               0.00      0.00              0.00
Blue Origin           0.00      0.00              0.00
AEB                   0.00       NaN               NaN
ASI                   0.00      0.00              0.00
AMBA                  0.00      0.00              0.00
Arm??e de l'Air       0.00      0.00              0.00
CASIC                 0.00      0.00              0.00
RAE                   0.00      0.00              0.00
OneSpace              0.00       NaN               NaN
OKB-586               0.00      0.00              0.00
MITT                  0.00      0.00              0.00
Khrunichev            0.00      0.00              0.00
KCST                  0.00      0.00              0.00
Land Launch           0.00      0.00              0.00
Landspace             0.00       NaN               NaN
KARI                  0.00      0.00              0.00
Starsem               0.00      0.00              0.00
SRC                   0.00      0.00              0.00
Sea Launch            0.00      0.00              0.00
UT                    0.00      0.00              0.00
US Navy               0.00      0.00              0.00
Yuzhmash              0.00      0.00              0.00
i-Space               0.00      0.00              0.00

In [75]:
percentage_df = (cost_comparison_df['Price_y']/cost_comparison_df['Price_x'])*100

In [76]:
percentage_df

Organisation
NASA                 97.299423
Arianespace          97.326400
ULA                  99.263414
RVSN USSR           100.000000
CASC                 95.471637
SpaceX               96.344600
Northrop             89.440204
MHI                 100.000000
ISRO                 85.484612
US Air Force         88.314678
VKS RF               90.406095
ILS                 100.000000
Boeing               71.796938
Roscosmos            95.915789
Martin Marietta      76.212919
Kosmotras            95.454545
Eurockot             92.307692
Lockheed            100.000000
JAXA                100.000000
Rocket Lab           84.615385
ESA                 100.000000
ExPace                0.000000
EER                        NaN
Sandia                     NaN
Virgin Orbit               NaN
ISAS                       NaN
IRGC                       NaN
ISA                        NaN
Exos                       NaN
General Dynamics           NaN
CECLES                     NaN
IAI                        NaN
CNES                       NaN
Douglas                    NaN
Blue Origin                NaN
AEB                        NaN
ASI                        NaN
AMBA                       NaN
Arm??e de l'Air            NaN
CASIC                      NaN
RAE                        NaN
OneSpace                   NaN
OKB-586                    NaN
MITT                       NaN
Khrunichev                 NaN
KCST                       NaN
Land Launch                NaN
Landspace                  NaN
KARI                       NaN
Starsem                    NaN
SRC                        NaN
Sea Launch                 NaN
UT                         NaN
US Navy                    NaN
Yuzhmash                   NaN
i-Space                    NaN
dtype: float64

In [77]:
cost_comparison_df['percent_cost_successful_missions'] = percentage_df

In [78]:
cost_comparison_df

,Price_x,Price_y,cost_of_failures,percent_cost_successful_missions
Organisation,,,,
NASA,76280.00,74220.00,2060.00,97.299423
Arianespace,16345.00,15908.00,437.00,97.326400
ULA,14798.00,14689.00,109.00,99.263414
RVSN USSR,10000.00,10000.00,0.00,100.000000
CASC,6340.26,6053.15,287.11,95.471637
SpaceX,5444.00,5245.00,199.00,96.344600
Northrop,3930.00,3515.00,415.00,89.440204
MHI,3532.50,3532.50,0.00,100.000000
ISRO,2177.00,1861.00,316.00,85.484612
US Air Force,1550.92,1369.69,181.23,88.314678
VKS RF,1548.90,1400.30,148.60,90.406095
ILS,1320.00,1320.00,0.00,100.000000
Boeing,1241.00,891.00,350.00,71.796938
Roscosmos,1187.50,1139.00,48.50,95.915789
Martin Marietta,721.40,549.80,171.60,76.212919
Kosmotras,638.00,609.00,29.00,95.454545
Eurockot,543.40,501.60,41.80,92.307692
Lockheed,280.00,280.00,0.00,100.000000
JAXA,168.00,168.00,0.00,100.000000
Rocket Lab,97.50,82.50,15.00,84.615385
ESA,37.00,37.00,0.00,100.000000
ExPace,28.30,0.00,28.30,0.000000
EER,20.00,NaN,NaN,NaN
Sandia,15.00,NaN,NaN,NaN
Virgin Orbit,12.00,NaN,NaN,NaN
ISAS,0.00,0.00,0.00,NaN
IRGC,0.00,0.00,0.00,NaN
ISA,0.00,0.00,0.00,NaN
Exos,0.00,NaN,NaN,NaN
General Dynamics,0.00,0.00,0.00,NaN
CECLES,0.00,0.00,0.00,NaN
IAI,0.00,0.00,0.00,NaN
CNES,0.00,0.00,0.00,NaN
Douglas,0.00,0.00,0.00,NaN
Blue Origin,0.00,0.00,0.00,NaN
AEB,0.00,NaN,NaN,NaN
ASI,0.00,0.00,0.00,NaN
AMBA,0.00,0.00,0.00,NaN
Arm??e de l'Air,0.00,0.00,0.00,NaN
CASIC,0.00,0.00,0.00,NaN
RAE,0.00,0.00,0.00,NaN
OneSpace,0.00,NaN,NaN,NaN
OKB-586,0.00,0.00,0.00,NaN
MITT,0.00,0.00,0.00,NaN
Khrunichev,0.00,0.00,0.00,NaN
KCST,0.00,0.00,0.00,NaN
Land Launch,0.00,0.00,0.00,NaN
Landspace,0.00,NaN,NaN,NaN
KARI,0.00,0.00,0.00,NaN
Starsem,0.00,0.00,0.00,NaN
SRC,0.00,0.00,0.00,NaN
Sea Launch,0.00,0.00,0.00,NaN
UT,0.00,0.00,0.00,NaN
US Navy,0.00,0.00,0.00,NaN
Yuzhmash,0.00,0.00,0.00,NaN
i-Space,0.00,0.00,0.00,NaN

In [79]:
total_of_each = df.groupby('Organisation').agg({'Organisation':pd.Series.count})

In [80]:
total_of_each.columns = ['Count_of_missions']

In [81]:
total_of_each.sort_values(by='Count_of_missions', ascending=False, inplace=True)

In [82]:
total_of_each

                  Count_of_missions
Organisation
RVSN USSR                      1777
Arianespace                     279
General Dynamics                251
CASC                            251
NASA                            203
VKS RF                          201
US Air Force                    161
ULA                             140
Boeing                          136
Martin Marietta                 114
SpaceX                          100
MHI                              84
Northrop                         83
Lockheed                         79
ISRO                             76
Roscosmos                        55
ILS                              46
Sea Launch                       36
ISAS                             30
Kosmotras                        22
US Navy                          17
ESA                              13
ISA                              13
Eurockot                         13
Rocket Lab                       13
Blue Origin                      12
IAI                              11
ExPace                           10
ASI                               9
AMBA                              8
CNES                              8
JAXA                              7
Land Launch                       7
MITT                              7
KCST                              5
UT                                5
CASIC                             5
CECLES                            4
Arm??e de l'Air                   4
Exos                              4
SRC                               3
KARI                              3
AEB                               3
OKB-586                           2
Yuzhmash                          2
RAE                               2
Douglas                           1
EER                               1
IRGC                              1
OneSpace                          1
Khrunichev                        1
Landspace                         1
Starsem                           1
Sandia                            1
Virgin Orbit                      1
i-Space                           1

In [83]:
sum_df = total_of_each['Count_of_missions'].sum()

In [84]:
sum_df

np.int64(4324)

In [85]:
total_of_each['percent_distribution'] = (total_of_each['Count_of_missions']/sum_df)*100

In [86]:
total_of_each

                  Count_of_missions  percent_distribution
Organisation
RVSN USSR                      1777             41.096207
Arianespace                     279              6.452359
General Dynamics                251              5.804810
CASC                            251              5.804810
NASA                            203              4.694727
VKS RF                          201              4.648474
US Air Force                    161              3.723404
ULA                             140              3.237743
Boeing                          136              3.145236
Martin Marietta                 114              2.636448
SpaceX                          100              2.312673
MHI                              84              1.942646
Northrop                         83              1.919519
Lockheed                         79              1.827012
ISRO                             76              1.757632
Roscosmos                        55              1.271970
ILS                              46              1.063830
Sea Launch                       36              0.832562
ISAS                             30              0.693802
Kosmotras                        22              0.508788
US Navy                          17              0.393154
ESA                              13              0.300648
ISA                              13              0.300648
Eurockot                         13              0.300648
Rocket Lab                       13              0.300648
Blue Origin                      12              0.277521
IAI                              11              0.254394
ExPace                           10              0.231267
ASI                               9              0.208141
AMBA                              8              0.185014
CNES                              8              0.185014
JAXA                              7              0.161887
Land Launch                       7              0.161887
MITT                              7              0.161887
KCST                              5              0.115634
UT                                5              0.115634
CASIC                             5              0.115634
CECLES                            4              0.092507
Arm??e de l'Air                   4              0.092507
Exos                              4              0.092507
SRC                               3              0.069380
KARI                              3              0.069380
AEB                               3              0.069380
OKB-586                           2              0.046253
Yuzhmash                          2              0.046253
RAE                               2              0.046253
Douglas                           1              0.023127
EER                               1              0.023127
IRGC                              1              0.023127
OneSpace                          1              0.023127
Khrunichev                        1              0.023127
Landspace                         1              0.023127
Starsem                           1              0.023127
Sandia                            1              0.023127
Virgin Orbit                      1              0.023127
i-Space                           1              0.023127

In [87]:
total_of_each_top5 = total_of_each.head()

In [88]:
total_of_each_top5

                  Count_of_missions  percent_distribution
Organisation
RVSN USSR                      1777             41.096207
Arianespace                     279              6.452359
General Dynamics                251              5.804810
CASC                            251              5.804810
NASA                            203              4.694727

In [89]:
#important
top_10 = 10
total_of_each_top = total_of_each.iloc[:top_10].copy()
total_of_each_remaining_count = total_of_each.iloc[top_10:]['Count_of_missions'].sum()
total_of_each_remaining_percentage = total_of_each.iloc[top_10:]['percent_distribution'].sum()
other_row = pd.DataFrame({
    'Count_of_missions': [total_of_each_remaining_count],
    'percent_distribution': [total_of_each_remaining_percentage]
}, index=['Other small organisations'])
df_final = pd.concat([total_of_each_top, other_row])
df_final

                           Count_of_missions  percent_distribution
RVSN USSR                               1777             41.096207
Arianespace                              279              6.452359
General Dynamics                         251              5.804810
CASC                                     251              5.804810
NASA                                     203              4.694727
VKS RF                                   201              4.648474
US Air Force                             161              3.723404
ULA                                      140              3.237743
Boeing                                   136              3.145236
Martin Marietta                          114              2.636448
Other small organisations                811             18.755782

In [90]:
donut = px.pie(df_final, values=df_final.percent_distribution, names=df_final.index, hole=0.7, title='distribution of space missions conducted by each organisation')
donut.update_traces(textposition='inside')
donut.show()

In [91]:
success_count

,Unnamed: 0.1,Unnamed: 0,Organisation,Location,Date,Detail,Rocket_Status,Price,Mission_Status,year
0,0,0,SpaceX,"LC-39A, Kennedy Space Center, Florida, USA",2020-08-07 05:12:00+00:00,Falcon 9 Block 5 | Starlink V1 L9 & BlackSky,StatusActive,50.00,Success,2020
1,1,1,CASC,"Site 9401 (SLS-2), Jiuquan Satellite Launch Ce...",2020-08-06 04:01:00+00:00,Long March 2D | Gaofen-9 04 & Q-SAT,StatusActive,29.75,Success,2020
2,2,2,SpaceX,"Pad A, Boca Chica, Texas, USA",2020-08-04 23:57:00+00:00,Starship Prototype | 150 Meter Hop,StatusActive,NaN,Success,2020
3,3,3,Roscosmos,"Site 200/39, Baikonur Cosmodrome, Kazakhstan",2020-07-30 21:25:00+00:00,Proton-M/Briz-M | Ekspress-80 & Ekspress-103,StatusActive,65.00,Success,2020
4,4,4,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA",2020-07-30 11:50:00+00:00,Atlas V 541 | Perseverance,StatusActive,145.00,Success,2020
...,...,...,...,...,...,...,...,...,...,...
4316,4316,4316,AMBA,"LC-5, Cape Canaveral AFS, Florida, USA",1958-03-26 17:38:00+00:00,Juno I | Explorer 3,StatusRetired,NaN,Success,1958
4317,4317,4317,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1958-03-17 12:15:00+00:00,Vanguard | Vanguard 1,StatusRetired,NaN,Success,1958
4320,4320,4320,AMBA,"LC-26A, Cape Canaveral AFS, Florida, USA",1958-02-01 03:48:00+00:00,Juno I | Explorer 1,StatusRetired,NaN,Success,1958
4322,4322,4322,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-11-03 02:30:00+00:00,Sputnik 8K71PS | Sputnik-2,StatusRetired,NaN,Success,1957
4323,4323,4323,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-10-04 19:28:00+00:00,Sputnik 8K71PS | Sputnik-1,StatusRetired,NaN,Success,1957

In [92]:
pre_USSR_collapse = success_count.query("year >= 1957 and year <=1990")
pre_USSR_Collapse = pre_USSR_collapse[pre_USSR_collapse['Organisation'].isin(['RVSN USSR','Roscosmos'])]
pre_USSR_Collapse.groupby('Organisation').agg({'Organisation':pd.Series.value_counts})

              Organisation
Organisation
RVSN USSR             1577
Roscosmos                1

In [93]:
post_USSR_collapse = success_count.query("year >= 1991 and year <= 2020")
post_USSR_Collapse = post_USSR_collapse[post_USSR_collapse['Organisation'].isin(['RVSN USSR','Roscosmos'])]
post_USSR_Collapse.groupby('Organisation').agg({'Organisation':pd.Series.value_counts})

              Organisation
Organisation
RVSN USSR               37
Roscosmos               50

In [94]:
post_USSR_collapse = success_count.query("year >= 1991 and year <= 2020")

In [95]:
avg_success_operation_cost_post_USSR = post_USSR_collapse.Price.mean()

In [96]:
avg_success_operation_cost_post_USSR

np.float64(122.59300486618002)

In [97]:
avg_success_operation_cost_pre_USSR = pre_USSR_collapse.Price.mean()

In [98]:
avg_success_operation_cost_pre_USSR

np.float64(484.09193181818176)

In [99]:
success_Count = df[df['Mission_Status'] == 'Success']

In [100]:
sc= success_Count.groupby('Organisation')['Organisation'].value_counts()

In [101]:
unsuccessful_count = df[df['Mission_Status'] == 'Failure']

In [102]:
uc = unsuccessful_count.groupby('Organisation')['Organisation'].value_counts()

In [103]:
pd_success_df = pd.merge(sc, uc, on='Organisation', how='left')

In [104]:
pd_success_df

                  count_x  count_y
Organisation
AMBA                    4      3.0
ASI                     9      NaN
Arianespace           269      7.0
Arm??e de l'Air         3      NaN
Blue Origin            12      NaN
Boeing                131      3.0
CASC                  231     14.0
CASIC                   3      2.0
CECLES                  1      3.0
CNES                    6      2.0
Douglas                 1      NaN
ESA                     9      3.0
Eurockot               12      1.0
ExPace                  9      1.0
General Dynamics      203     37.0
IAI                     9      2.0
ILS                    45      NaN
IRGC                    1      NaN
ISA                     4      8.0
ISAS                   26      3.0
ISRO                   63      8.0
JAXA                    6      1.0
KARI                    1      2.0
KCST                    2      3.0
Khrunichev              1      NaN
Kosmotras              21      1.0
Land Launch             6      NaN
Lockheed               74      5.0
MHI                    80      2.0
MITT                    6      1.0
Martin Marietta       100     11.0
NASA                  186     11.0
Northrop               74      7.0
OKB-586                 2      NaN
RAE                     1      1.0
RVSN USSR            1614    121.0
Rocket Lab             11      2.0
Roscosmos              51      3.0
SRC                     2      1.0
Sea Launch             33      3.0
SpaceX                 94      4.0
Starsem                 1      NaN
ULA                   139      NaN
US Air Force          129     30.0
US Navy                 2     14.0
UT                      1      4.0
VKS RF                188      7.0
Yuzhmash                2      NaN
i-Space                 1      NaN

In [105]:
pd_success_df['Success Rate'] = (pd_success_df['count_x']/(pd_success_df['count_y']+pd_success_df['count_x']))*100

In [106]:
pd_success_df

                  count_x  count_y  Success Rate
Organisation
AMBA                    4      3.0     57.142857
ASI                     9      NaN           NaN
Arianespace           269      7.0     97.463768
Arm??e de l'Air         3      NaN           NaN
Blue Origin            12      NaN           NaN
Boeing                131      3.0     97.761194
CASC                  231     14.0     94.285714
CASIC                   3      2.0     60.000000
CECLES                  1      3.0     25.000000
CNES                    6      2.0     75.000000
Douglas                 1      NaN           NaN
ESA                     9      3.0     75.000000
Eurockot               12      1.0     92.307692
ExPace                  9      1.0     90.000000
General Dynamics      203     37.0     84.583333
IAI                     9      2.0     81.818182
ILS                    45      NaN           NaN
IRGC                    1      NaN           NaN
ISA                     4      8.0     33.333333
ISAS                   26      3.0     89.655172
ISRO                   63      8.0     88.732394
JAXA                    6      1.0     85.714286
KARI                    1      2.0     33.333333
KCST                    2      3.0     40.000000
Khrunichev              1      NaN           NaN
Kosmotras              21      1.0     95.454545
Land Launch             6      NaN           NaN
Lockheed               74      5.0     93.670886
MHI                    80      2.0     97.560976
MITT                    6      1.0     85.714286
Martin Marietta       100     11.0     90.090090
NASA                  186     11.0     94.416244
Northrop               74      7.0     91.358025
OKB-586                 2      NaN           NaN
RAE                     1      1.0     50.000000
RVSN USSR            1614    121.0     93.025937
Rocket Lab             11      2.0     84.615385
Roscosmos              51      3.0     94.444444
SRC                     2      1.0     66.666667
Sea Launch             33      3.0     91.666667
SpaceX                 94      4.0     95.918367
Starsem                 1      NaN           NaN
ULA                   139      NaN           NaN
US Air Force          129     30.0     81.132075
US Navy                 2     14.0     12.500000
UT                      1      4.0     20.000000
VKS RF                188      7.0     96.410256
Yuzhmash                2      NaN           NaN
i-Space                 1      NaN           NaN

In [107]:
pd_success_df.sort_index(inplace=True)

In [108]:
pd_success_df

                  count_x  count_y  Success Rate
Organisation
AMBA                    4      3.0     57.142857
ASI                     9      NaN           NaN
Arianespace           269      7.0     97.463768
Arm??e de l'Air         3      NaN           NaN
Blue Origin            12      NaN           NaN
Boeing                131      3.0     97.761194
CASC                  231     14.0     94.285714
CASIC                   3      2.0     60.000000
CECLES                  1      3.0     25.000000
CNES                    6      2.0     75.000000
Douglas                 1      NaN           NaN
ESA                     9      3.0     75.000000
Eurockot               12      1.0     92.307692
ExPace                  9      1.0     90.000000
General Dynamics      203     37.0     84.583333
IAI                     9      2.0     81.818182
ILS                    45      NaN           NaN
IRGC                    1      NaN           NaN
ISA                     4      8.0     33.333333
ISAS                   26      3.0     89.655172
ISRO                   63      8.0     88.732394
JAXA                    6      1.0     85.714286
KARI                    1      2.0     33.333333
KCST                    2      3.0     40.000000
Khrunichev              1      NaN           NaN
Kosmotras              21      1.0     95.454545
Land Launch             6      NaN           NaN
Lockheed               74      5.0     93.670886
MHI                    80      2.0     97.560976
MITT                    6      1.0     85.714286
Martin Marietta       100     11.0     90.090090
NASA                  186     11.0     94.416244
Northrop               74      7.0     91.358025
OKB-586                 2      NaN           NaN
RAE                     1      1.0     50.000000
RVSN USSR            1614    121.0     93.025937
Rocket Lab             11      2.0     84.615385
Roscosmos              51      3.0     94.444444
SRC                     2      1.0     66.666667
Sea Launch             33      3.0     91.666667
SpaceX                 94      4.0     95.918367
Starsem                 1      NaN           NaN
ULA                   139      NaN           NaN
US Air Force          129     30.0     81.132075
US Navy                 2     14.0     12.500000
UT                      1      4.0     20.000000
VKS RF                188      7.0     96.410256
Yuzhmash                2      NaN           NaN
i-Space                 1      NaN           NaN

In [109]:
pd_success_df.drop(columns=['count_y','count_x'])

                  Success Rate
Organisation
AMBA                 57.142857
ASI                        NaN
Arianespace          97.463768
Arm??e de l'Air            NaN
Blue Origin                NaN
Boeing               97.761194
CASC                 94.285714
CASIC                60.000000
CECLES               25.000000
CNES                 75.000000
Douglas                    NaN
ESA                  75.000000
Eurockot             92.307692
ExPace               90.000000
General Dynamics     84.583333
IAI                  81.818182
ILS                        NaN
IRGC                       NaN
ISA                  33.333333
ISAS                 89.655172
ISRO                 88.732394
JAXA                 85.714286
KARI                 33.333333
KCST                 40.000000
Khrunichev                 NaN
Kosmotras            95.454545
Land Launch                NaN
Lockheed             93.670886
MHI                  97.560976
MITT                 85.714286
Martin Marietta      90.090090
NASA                 94.416244
Northrop             91.358025
OKB-586                    NaN
RAE                  50.000000
RVSN USSR            93.025937
Rocket Lab           84.615385
Roscosmos            94.444444
SRC                  66.666667
Sea Launch           91.666667
SpaceX               95.918367
Starsem                    NaN
ULA                        NaN
US Air Force         81.132075
US Navy              12.500000
UT                   20.000000
VKS RF               96.410256
Yuzhmash                   NaN
i-Space                    NaN

In [110]:
avg_cost_per_organisation = df.groupby('Organisation').agg({'Price':pd.Series.mean})

In [111]:
avg_cost_per_organisation

                        Price
Organisation
AEB                       NaN
AMBA                      NaN
ASI                       NaN
Arianespace        170.260417
Arm??e de l'Air           NaN
Blue Origin               NaN
Boeing             177.285714
CASC                40.128228
CASIC                     NaN
CECLES                    NaN
CNES                      NaN
Douglas                   NaN
EER                 20.000000
ESA                 37.000000
Eurockot            41.800000
ExPace              28.300000
Exos                      NaN
General Dynamics          NaN
IAI                       NaN
ILS                101.538462
IRGC                      NaN
ISA                       NaN
ISAS                      NaN
ISRO                32.492537
JAXA                56.000000
KARI                      NaN
KCST                      NaN
Khrunichev                NaN
Kosmotras           29.000000
Land Launch               NaN
Landspace                 NaN
Lockheed            35.000000
MHI                 95.472973
MITT                      NaN
Martin Marietta     80.155556
NASA               511.946309
Northrop            47.349398
OKB-586                   NaN
OneSpace                  NaN
RAE                       NaN
RVSN USSR         5000.000000
Rocket Lab           7.500000
Roscosmos           51.630435
SRC                       NaN
Sandia              15.000000
Sea Launch                NaN
SpaceX              54.989899
Starsem                   NaN
ULA                151.000000
US Air Force        59.650769
US Navy                   NaN
UT                        NaN
VKS RF              46.936364
Virgin Orbit        12.000000
Yuzhmash                  NaN
i-Space                   NaN

In [112]:
df_comparison = pd.merge(pd_success_df, avg_cost_per_organisation, on='Organisation', how='left')

In [113]:
df_comparison.drop(columns=['count_y','count_x'], inplace=True)

In [114]:
df_comparison

                  Success Rate        Price
Organisation
AMBA                 57.142857          NaN
ASI                        NaN          NaN
Arianespace          97.463768   170.260417
Arm??e de l'Air            NaN          NaN
Blue Origin                NaN          NaN
Boeing               97.761194   177.285714
CASC                 94.285714    40.128228
CASIC                60.000000          NaN
CECLES               25.000000          NaN
CNES                 75.000000          NaN
Douglas                    NaN          NaN
ESA                  75.000000    37.000000
Eurockot             92.307692    41.800000
ExPace               90.000000    28.300000
General Dynamics     84.583333          NaN
IAI                  81.818182          NaN
ILS                        NaN   101.538462
IRGC                       NaN          NaN
ISA                  33.333333          NaN
ISAS                 89.655172          NaN
ISRO                 88.732394    32.492537
JAXA                 85.714286    56.000000
KARI                 33.333333          NaN
KCST                 40.000000          NaN
Khrunichev                 NaN          NaN
Kosmotras            95.454545    29.000000
Land Launch                NaN          NaN
Lockheed             93.670886    35.000000
MHI                  97.560976    95.472973
MITT                 85.714286          NaN
Martin Marietta      90.090090    80.155556
NASA                 94.416244   511.946309
Northrop             91.358025    47.349398
OKB-586                    NaN          NaN
RAE                  50.000000          NaN
RVSN USSR            93.025937  5000.000000
Rocket Lab           84.615385     7.500000
Roscosmos            94.444444    51.630435
SRC                  66.666667          NaN
Sea Launch           91.666667          NaN
SpaceX               95.918367    54.989899
Starsem                    NaN          NaN
ULA                        NaN   151.000000
US Air Force         81.132075    59.650769
US Navy              12.500000          NaN
UT                   20.000000          NaN
VKS RF               96.410256    46.936364
Yuzhmash                   NaN          NaN
i-Space                    NaN          NaN

In [115]:
df_comparison.dropna(subset=['Success Rate','Price'], inplace=True)

In [116]:
df_comparison.sort_values(by='Success Rate', ascending=False, inplace=True)

In [117]:
df_comparison

                 Success Rate        Price
Organisation
Boeing              97.761194   177.285714
MHI                 97.560976    95.472973
Arianespace         97.463768   170.260417
VKS RF              96.410256    46.936364
SpaceX              95.918367    54.989899
Kosmotras           95.454545    29.000000
Roscosmos           94.444444    51.630435
NASA                94.416244   511.946309
CASC                94.285714    40.128228
Lockheed            93.670886    35.000000
RVSN USSR           93.025937  5000.000000
Eurockot            92.307692    41.800000
Northrop            91.358025    47.349398
Martin Marietta     90.090090    80.155556
ExPace              90.000000    28.300000
ISRO                88.732394    32.492537
JAXA                85.714286    56.000000
Rocket Lab          84.615385     7.500000
US Air Force        81.132075    59.650769
ESA                 75.000000    37.000000

In [118]:
df_comparison.corr()

              Success Rate     Price
Success Rate      1.000000  0.089009
Price             0.089009  1.000000

In [119]:
scatterPlot = px.scatter(df_comparison, x='Success Rate', y='Price', title='Succes Rate v/s Price', color='Success Rate', hover_name=df_comparison.index, size='Price', size_max=60)
scatterPlot.show()

In [120]:
df_comparison

                 Success Rate        Price
Organisation
Boeing              97.761194   177.285714
MHI                 97.560976    95.472973
Arianespace         97.463768   170.260417
VKS RF              96.410256    46.936364
SpaceX              95.918367    54.989899
Kosmotras           95.454545    29.000000
Roscosmos           94.444444    51.630435
NASA                94.416244   511.946309
CASC                94.285714    40.128228
Lockheed            93.670886    35.000000
RVSN USSR           93.025937  5000.000000
Eurockot            92.307692    41.800000
Northrop            91.358025    47.349398
Martin Marietta     90.090090    80.155556
ExPace              90.000000    28.300000
ISRO                88.732394    32.492537
JAXA                85.714286    56.000000
Rocket Lab          84.615385     7.500000
US Air Force        81.132075    59.650769
ESA                 75.000000    37.000000

In [121]:
weekend_takeoffs = df[df['Date'].dt.dayofweek > 5]
weekend_takeoffs.shape

(270, 10)

In [122]:
weekday_takeoffs = df[df['Date'].dt.dayofweek <= 5]
weekday_takeoffs.shape

(4054, 10)

In [123]:
df

,Unnamed: 0.1,Unnamed: 0,Organisation,Location,Date,Detail,Rocket_Status,Price,Mission_Status,year
0,0,0,SpaceX,"LC-39A, Kennedy Space Center, Florida, USA",2020-08-07 05:12:00+00:00,Falcon 9 Block 5 | Starlink V1 L9 & BlackSky,StatusActive,50.00,Success,2020
1,1,1,CASC,"Site 9401 (SLS-2), Jiuquan Satellite Launch Ce...",2020-08-06 04:01:00+00:00,Long March 2D | Gaofen-9 04 & Q-SAT,StatusActive,29.75,Success,2020
2,2,2,SpaceX,"Pad A, Boca Chica, Texas, USA",2020-08-04 23:57:00+00:00,Starship Prototype | 150 Meter Hop,StatusActive,NaN,Success,2020
3,3,3,Roscosmos,"Site 200/39, Baikonur Cosmodrome, Kazakhstan",2020-07-30 21:25:00+00:00,Proton-M/Briz-M | Ekspress-80 & Ekspress-103,StatusActive,65.00,Success,2020
4,4,4,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA",2020-07-30 11:50:00+00:00,Atlas V 541 | Perseverance,StatusActive,145.00,Success,2020
...,...,...,...,...,...,...,...,...,...,...
4319,4319,4319,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1958-02-05 07:33:00+00:00,Vanguard | Vanguard TV3BU,StatusRetired,NaN,Failure,1958
4320,4320,4320,AMBA,"LC-26A, Cape Canaveral AFS, Florida, USA",1958-02-01 03:48:00+00:00,Juno I | Explorer 1,StatusRetired,NaN,Success,1958
4321,4321,4321,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1957-12-06 16:44:00+00:00,Vanguard | Vanguard TV3,StatusRetired,NaN,Failure,1957
4322,4322,4322,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-11-03 02:30:00+00:00,Sputnik 8K71PS | Sputnik-2,StatusRetired,NaN,Success,1957
4323,4323,4323,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-10-04 19:28:00+00:00,Sputnik 8K71PS | Sputnik-1,StatusRetired,NaN,Success,1957

In [124]:
df_investments_after_collapse = df.query('year >= 1991')
df_investments_after_collapse.shape

(1776, 10)

In [125]:
df_investments_before_collapse = df.query('year < 1991')
df_investments_before_collapse.shape

(2548, 10)

In [126]:
df_dropping_na = df.dropna(subset=['Price'])

In [127]:
df_dropping_na[df_dropping_na['year'] >= 1991].shape

(870, 10)

In [128]:
df_dropping_na[df_dropping_na['year'] < 1991].shape

(94, 10)

In [129]:
df_nan_removed = df.dropna(subset=['Price'])

In [130]:
df

,Unnamed: 0.1,Unnamed: 0,Organisation,Location,Date,Detail,Rocket_Status,Price,Mission_Status,year
0,0,0,SpaceX,"LC-39A, Kennedy Space Center, Florida, USA",2020-08-07 05:12:00+00:00,Falcon 9 Block 5 | Starlink V1 L9 & BlackSky,StatusActive,50.00,Success,2020
1,1,1,CASC,"Site 9401 (SLS-2), Jiuquan Satellite Launch Ce...",2020-08-06 04:01:00+00:00,Long March 2D | Gaofen-9 04 & Q-SAT,StatusActive,29.75,Success,2020
2,2,2,SpaceX,"Pad A, Boca Chica, Texas, USA",2020-08-04 23:57:00+00:00,Starship Prototype | 150 Meter Hop,StatusActive,NaN,Success,2020
3,3,3,Roscosmos,"Site 200/39, Baikonur Cosmodrome, Kazakhstan",2020-07-30 21:25:00+00:00,Proton-M/Briz-M | Ekspress-80 & Ekspress-103,StatusActive,65.00,Success,2020
4,4,4,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA",2020-07-30 11:50:00+00:00,Atlas V 541 | Perseverance,StatusActive,145.00,Success,2020
...,...,...,...,...,...,...,...,...,...,...
4319,4319,4319,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1958-02-05 07:33:00+00:00,Vanguard | Vanguard TV3BU,StatusRetired,NaN,Failure,1958
4320,4320,4320,AMBA,"LC-26A, Cape Canaveral AFS, Florida, USA",1958-02-01 03:48:00+00:00,Juno I | Explorer 1,StatusRetired,NaN,Success,1958
4321,4321,4321,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1957-12-06 16:44:00+00:00,Vanguard | Vanguard TV3,StatusRetired,NaN,Failure,1957
4322,4322,4322,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-11-03 02:30:00+00:00,Sputnik 8K71PS | Sputnik-2,StatusRetired,NaN,Success,1957
4323,4323,4323,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-10-04 19:28:00+00:00,Sputnik 8K71PS | Sputnik-1,StatusRetired,NaN,Success,1957

In [131]:
df_nan_removed[df_nan_removed['year'] >= 1991].shape

(870, 10)

In [132]:
df_nan_removed[df_nan_removed['year'] < 1991].shape

(94, 10)

In [133]:
df[df['year'] >= 1991].shape

(1776, 10)

In [134]:
df[df['year'] < 1991].shape

(2548, 10)

In [135]:
scatterplot = px.scatter(df_nan_removed, x='year', y='Price', size='Price', color='Price', title='Data', hover_data='Organisation')
scatterplot.show()

In [136]:
df

,Unnamed: 0.1,Unnamed: 0,Organisation,Location,Date,Detail,Rocket_Status,Price,Mission_Status,year
0,0,0,SpaceX,"LC-39A, Kennedy Space Center, Florida, USA",2020-08-07 05:12:00+00:00,Falcon 9 Block 5 | Starlink V1 L9 & BlackSky,StatusActive,50.00,Success,2020
1,1,1,CASC,"Site 9401 (SLS-2), Jiuquan Satellite Launch Ce...",2020-08-06 04:01:00+00:00,Long March 2D | Gaofen-9 04 & Q-SAT,StatusActive,29.75,Success,2020
2,2,2,SpaceX,"Pad A, Boca Chica, Texas, USA",2020-08-04 23:57:00+00:00,Starship Prototype | 150 Meter Hop,StatusActive,NaN,Success,2020
3,3,3,Roscosmos,"Site 200/39, Baikonur Cosmodrome, Kazakhstan",2020-07-30 21:25:00+00:00,Proton-M/Briz-M | Ekspress-80 & Ekspress-103,StatusActive,65.00,Success,2020
4,4,4,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA",2020-07-30 11:50:00+00:00,Atlas V 541 | Perseverance,StatusActive,145.00,Success,2020
...,...,...,...,...,...,...,...,...,...,...
4319,4319,4319,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1958-02-05 07:33:00+00:00,Vanguard | Vanguard TV3BU,StatusRetired,NaN,Failure,1958
4320,4320,4320,AMBA,"LC-26A, Cape Canaveral AFS, Florida, USA",1958-02-01 03:48:00+00:00,Juno I | Explorer 1,StatusRetired,NaN,Success,1958
4321,4321,4321,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1957-12-06 16:44:00+00:00,Vanguard | Vanguard TV3,StatusRetired,NaN,Failure,1957
4322,4322,4322,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-11-03 02:30:00+00:00,Sputnik 8K71PS | Sputnik-2,StatusRetired,NaN,Success,1957
4323,4323,4323,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-10-04 19:28:00+00:00,Sputnik 8K71PS | Sputnik-1,StatusRetired,NaN,Success,1957

In [137]:
df_successes = df[df['Mission_Status'] == 'Success']

In [138]:
df_success_missions = df_successes.groupby('year').agg({'year':pd.Series.count})

In [139]:
df_success_missions.shape

(64, 1)

In [140]:
df_success_missions

      year
year
1957     2
1958     6
1959     8
1960    19
1961    32
...    ...
2016    86
2017    84
2018   113
2019   100
2020    57

[64 rows x 1 columns]

In [141]:
df_surge_percentage = df_success_missions.pct_change()

In [142]:
df_surge_percentage.columns = ['%age surge']

In [143]:
df_surge_percentage

      %age surge
year
1957         NaN
1958    2.000000
1959    0.333333
1960    1.375000
1961    0.684211
...          ...
2016    0.791667
2017   -0.023256
2018    0.345238
2019   -0.115044
2020   -0.430000

[64 rows x 1 columns]

In [144]:
df_surge_percentage['%age surge'].idxmax()

np.int32(1958)

In [145]:
#important
df_legacy_retired = df_successes.groupby('Organisation').agg(active_rocket_count=('Rocket_Status', lambda x: (x == 'StatusActive').sum()), retired_rocekt_count = ('Rocket_Status',lambda x: (x == 'StatusRetired').sum()))

In [147]:
df_legacy_retired.sort_values(by='retired_rocekt_count',ascending=False, inplace=True)

In [148]:
df_legacy_retired

                  active_rocket_count  retired_rocekt_count
Organisation
RVSN USSR                           0                  1614
General Dynamics                    0                   203
NASA                                0                   186
VKS RF                             25                   163
Arianespace                       110                   159
Boeing                              0                   131
US Air Force                        0                   129
Martin Marietta                     0                   100
Lockheed                            0                    74
SpaceX                             38                    56
ULA                                86                    53
MHI                                32                    48
ILS                                13                    32
CASC                              202                    29
ISAS                                0                    26
Kosmotras                           0                    21
Roscosmos                          30                    21
Northrop                           57                    17
ISRO                               48                    15
Eurockot                            0                    12
ASI                                 0                     9
ESA                                 1                     8
CNES                                0                     6
IAI                                 5                     4
AMBA                                0                     4
ISA                                 1                     3
Arm??e de l'Air                     0                     3
Yuzhmash                            0                     2
SRC                                 0                     2
CASIC                               1                     2
US Navy                             0                     2
OKB-586                             0                     2
Douglas                             0                     1
UT                                  0                     1
KARI                                0                     1
CECLES                              0                     1
RAE                                 0                     1
JAXA                                5                     1
Starsem                             0                     1
ExPace                              9                     0
Blue Origin                        12                     0
MITT                                6                     0
Land Launch                         6                     0
KCST                                2                     0
Khrunichev                          1                     0
IRGC                                1                     0
Rocket Lab                         11                     0
Sea Launch                         33                     0
i-Space                             1                     0

In [149]:
df

,Unnamed: 0.1,Unnamed: 0,Organisation,Location,Date,Detail,Rocket_Status,Price,Mission_Status,year
0,0,0,SpaceX,"LC-39A, Kennedy Space Center, Florida, USA",2020-08-07 05:12:00+00:00,Falcon 9 Block 5 | Starlink V1 L9 & BlackSky,StatusActive,50.00,Success,2020
1,1,1,CASC,"Site 9401 (SLS-2), Jiuquan Satellite Launch Ce...",2020-08-06 04:01:00+00:00,Long March 2D | Gaofen-9 04 & Q-SAT,StatusActive,29.75,Success,2020
2,2,2,SpaceX,"Pad A, Boca Chica, Texas, USA",2020-08-04 23:57:00+00:00,Starship Prototype | 150 Meter Hop,StatusActive,NaN,Success,2020
3,3,3,Roscosmos,"Site 200/39, Baikonur Cosmodrome, Kazakhstan",2020-07-30 21:25:00+00:00,Proton-M/Briz-M | Ekspress-80 & Ekspress-103,StatusActive,65.00,Success,2020
4,4,4,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA",2020-07-30 11:50:00+00:00,Atlas V 541 | Perseverance,StatusActive,145.00,Success,2020
...,...,...,...,...,...,...,...,...,...,...
4319,4319,4319,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1958-02-05 07:33:00+00:00,Vanguard | Vanguard TV3BU,StatusRetired,NaN,Failure,1958
4320,4320,4320,AMBA,"LC-26A, Cape Canaveral AFS, Florida, USA",1958-02-01 03:48:00+00:00,Juno I | Explorer 1,StatusRetired,NaN,Success,1958
4321,4321,4321,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1957-12-06 16:44:00+00:00,Vanguard | Vanguard TV3,StatusRetired,NaN,Failure,1957
4322,4322,4322,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-11-03 02:30:00+00:00,Sputnik 8K71PS | Sputnik-2,StatusRetired,NaN,Success,1957
4323,4323,4323,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-10-04 19:28:00+00:00,Sputnik 8K71PS | Sputnik-1,StatusRetired,NaN,Success,1957

In [150]:
life_span_orgs = df_nan_removed.groupby('Organisation').agg(min_year=('year', lambda x: x.min()), max_year=('year',lambda x:x.max()))
life_span_orgs

                 min_year  max_year
Organisation
Arianespace          2002      2020
Boeing               2002      2006
CASC                 1982      2020
EER                  1995      1995
ESA                  2012      2012
Eurockot             2000      2018
ExPace               2020      2020
ILS                  2002      2019
ISRO                 1993      2019
JAXA                 2018      2020
Kosmotras            1999      2015
Lockheed             1997      2003
MHI                  2001      2020
Martin Marietta      1988      1994
NASA                 1967      2011
Northrop             1990      2020
RVSN USSR            1987      1988
Rocket Lab           2017      2020
Roscosmos            2016      2020
Sandia               2015      2015
SpaceX               2006      2020
ULA                  2007      2020
US Air Force         1964      1969
VKS RF               2004      2020
Virgin Orbit         2020      2020

In [151]:
df

,Unnamed: 0.1,Unnamed: 0,Organisation,Location,Date,Detail,Rocket_Status,Price,Mission_Status,year
0,0,0,SpaceX,"LC-39A, Kennedy Space Center, Florida, USA",2020-08-07 05:12:00+00:00,Falcon 9 Block 5 | Starlink V1 L9 & BlackSky,StatusActive,50.00,Success,2020
1,1,1,CASC,"Site 9401 (SLS-2), Jiuquan Satellite Launch Ce...",2020-08-06 04:01:00+00:00,Long March 2D | Gaofen-9 04 & Q-SAT,StatusActive,29.75,Success,2020
2,2,2,SpaceX,"Pad A, Boca Chica, Texas, USA",2020-08-04 23:57:00+00:00,Starship Prototype | 150 Meter Hop,StatusActive,NaN,Success,2020
3,3,3,Roscosmos,"Site 200/39, Baikonur Cosmodrome, Kazakhstan",2020-07-30 21:25:00+00:00,Proton-M/Briz-M | Ekspress-80 & Ekspress-103,StatusActive,65.00,Success,2020
4,4,4,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA",2020-07-30 11:50:00+00:00,Atlas V 541 | Perseverance,StatusActive,145.00,Success,2020
...,...,...,...,...,...,...,...,...,...,...
4319,4319,4319,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1958-02-05 07:33:00+00:00,Vanguard | Vanguard TV3BU,StatusRetired,NaN,Failure,1958
4320,4320,4320,AMBA,"LC-26A, Cape Canaveral AFS, Florida, USA",1958-02-01 03:48:00+00:00,Juno I | Explorer 1,StatusRetired,NaN,Success,1958
4321,4321,4321,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1957-12-06 16:44:00+00:00,Vanguard | Vanguard TV3,StatusRetired,NaN,Failure,1957
4322,4322,4322,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-11-03 02:30:00+00:00,Sputnik 8K71PS | Sputnik-2,StatusRetired,NaN,Success,1957
4323,4323,4323,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-10-04 19:28:00+00:00,Sputnik 8K71PS | Sputnik-1,StatusRetired,NaN,Success,1957

In [153]:
df['Country'] = df['Location'].apply(lambda x:x.split(',')[-1].strip())

In [155]:
df['Country']

0              USA
1            China
2              USA
3       Kazakhstan
4              USA
           ...
4319           USA
4320           USA
4321           USA
4322    Kazakhstan
4323    Kazakhstan
Name: Country, Length: 4324, dtype: object

In [156]:
df

,Unnamed: 0.1,Unnamed: 0,Organisation,Location,Date,Detail,Rocket_Status,Price,Mission_Status,year,Country
0,0,0,SpaceX,"LC-39A, Kennedy Space Center, Florida, USA",2020-08-07 05:12:00+00:00,Falcon 9 Block 5 | Starlink V1 L9 & BlackSky,StatusActive,50.00,Success,2020,USA
1,1,1,CASC,"Site 9401 (SLS-2), Jiuquan Satellite Launch Ce...",2020-08-06 04:01:00+00:00,Long March 2D | Gaofen-9 04 & Q-SAT,StatusActive,29.75,Success,2020,China
2,2,2,SpaceX,"Pad A, Boca Chica, Texas, USA",2020-08-04 23:57:00+00:00,Starship Prototype | 150 Meter Hop,StatusActive,NaN,Success,2020,USA
3,3,3,Roscosmos,"Site 200/39, Baikonur Cosmodrome, Kazakhstan",2020-07-30 21:25:00+00:00,Proton-M/Briz-M | Ekspress-80 & Ekspress-103,StatusActive,65.00,Success,2020,Kazakhstan
4,4,4,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA",2020-07-30 11:50:00+00:00,Atlas V 541 | Perseverance,StatusActive,145.00,Success,2020,USA
...,...,...,...,...,...,...,...,...,...,...,...
4319,4319,4319,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1958-02-05 07:33:00+00:00,Vanguard | Vanguard TV3BU,StatusRetired,NaN,Failure,1958,USA
4320,4320,4320,AMBA,"LC-26A, Cape Canaveral AFS, Florida, USA",1958-02-01 03:48:00+00:00,Juno I | Explorer 1,StatusRetired,NaN,Success,1958,USA
4321,4321,4321,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1957-12-06 16:44:00+00:00,Vanguard | Vanguard TV3,StatusRetired,NaN,Failure,1957,USA
4322,4322,4322,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-11-03 02:30:00+00:00,Sputnik 8K71PS | Sputnik-2,StatusRetired,NaN,Success,1957,Kazakhstan
4323,4323,4323,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-10-04 19:28:00+00:00,Sputnik 8K71PS | Sputnik-1,StatusRetired,NaN,Success,1957,Kazakhstan

In [157]:
df

,Unnamed: 0.1,Unnamed: 0,Organisation,Location,Date,Detail,Rocket_Status,Price,Mission_Status,year,Country
0,0,0,SpaceX,"LC-39A, Kennedy Space Center, Florida, USA",2020-08-07 05:12:00+00:00,Falcon 9 Block 5 | Starlink V1 L9 & BlackSky,StatusActive,50.00,Success,2020,USA
1,1,1,CASC,"Site 9401 (SLS-2), Jiuquan Satellite Launch Ce...",2020-08-06 04:01:00+00:00,Long March 2D | Gaofen-9 04 & Q-SAT,StatusActive,29.75,Success,2020,China
2,2,2,SpaceX,"Pad A, Boca Chica, Texas, USA",2020-08-04 23:57:00+00:00,Starship Prototype | 150 Meter Hop,StatusActive,NaN,Success,2020,USA
3,3,3,Roscosmos,"Site 200/39, Baikonur Cosmodrome, Kazakhstan",2020-07-30 21:25:00+00:00,Proton-M/Briz-M | Ekspress-80 & Ekspress-103,StatusActive,65.00,Success,2020,Kazakhstan
4,4,4,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA",2020-07-30 11:50:00+00:00,Atlas V 541 | Perseverance,StatusActive,145.00,Success,2020,USA
...,...,...,...,...,...,...,...,...,...,...,...
4319,4319,4319,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1958-02-05 07:33:00+00:00,Vanguard | Vanguard TV3BU,StatusRetired,NaN,Failure,1958,USA
4320,4320,4320,AMBA,"LC-26A, Cape Canaveral AFS, Florida, USA",1958-02-01 03:48:00+00:00,Juno I | Explorer 1,StatusRetired,NaN,Success,1958,USA
4321,4321,4321,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1957-12-06 16:44:00+00:00,Vanguard | Vanguard TV3,StatusRetired,NaN,Failure,1957,USA
4322,4322,4322,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-11-03 02:30:00+00:00,Sputnik 8K71PS | Sputnik-2,StatusRetired,NaN,Success,1957,Kazakhstan
4323,4323,4323,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-10-04 19:28:00+00:00,Sputnik 8K71PS | Sputnik-1,StatusRetired,NaN,Success,1957,Kazakhstan

In [161]:
df_countrywise_launches = df.groupby('Country').agg({'Country':pd.Series.count})
df_countrywise_launches_after_USSR  =df.query('year > 1991')
df_countrywise_launches_after_USSR_collapse = df_countrywise_launches_after_USSR.groupby('Country').agg({'Country':pd.Series.count})
df_countrywise_launches_after_USSR_collapse

                                Country
Country
Barents Sea                           3
Brazil                                3
China                               230
France                              242
Gran Canaria                          2
India                                69
Iran                                 13
Israel                                9
Japan                                74
Kazakhstan                          119
New Mexico                            4
New Zealand                          13
North Korea                           5
Pacific Missile Range Facility        1
Pacific Ocean                        36
Russia                              207
Shahrud Missile Test Site             1
South Korea                           3
USA                                 682
Yellow Sea                            1

In [164]:
df_countrywise_launches_after_USSR_collapse.columns = ['no. of missions']

In [165]:
df_countrywise_launches_after_USSR_collapse

                                no. of missions
Country
Barents Sea                                   3
Brazil                                        3
China                                       230
France                                      242
Gran Canaria                                  2
India                                        69
Iran                                         13
Israel                                        9
Japan                                        74
Kazakhstan                                  119
New Mexico                                    4
New Zealand                                  13
North Korea                                   5
Pacific Missile Range Facility                1
Pacific Ocean                                36
Russia                                      207
Shahrud Missile Test Site                     1
South Korea                                   3
USA                                         682
Yellow Sea                                    1

In [183]:
fig = px.choropleth(df_countrywise_launches_after_USSR_collapse,
                    locations='Country',
                    locationmode="country names",
                    color='no. of missions',
                    hover_name='Country',
                    hover_data=['no. of missions'],
                    scope="world",
                    color_continuous_scale="Reds",
                    title='Number of Missions by Country After USSR Collapse')

fig.show()

In [184]:
df

,Unnamed: 0.1,Unnamed: 0,Organisation,Location,Date,Detail,Rocket_Status,Price,Mission_Status,year,Country,states/provinces
0,0,0,SpaceX,"LC-39A, Kennedy Space Center, Florida, USA",2020-08-07 05:12:00+00:00,Falcon 9 Block 5 | Starlink V1 L9 & BlackSky,StatusActive,50.00,Success,2020,USA,[Florida]
1,1,1,CASC,"Site 9401 (SLS-2), Jiuquan Satellite Launch Ce...",2020-08-06 04:01:00+00:00,Long March 2D | Gaofen-9 04 & Q-SAT,StatusActive,29.75,Success,2020,China,"[Jiuquan, Satellite, Launch, Center]"
2,2,2,SpaceX,"Pad A, Boca Chica, Texas, USA",2020-08-04 23:57:00+00:00,Starship Prototype | 150 Meter Hop,StatusActive,NaN,Success,2020,USA,[Texas]
3,3,3,Roscosmos,"Site 200/39, Baikonur Cosmodrome, Kazakhstan",2020-07-30 21:25:00+00:00,Proton-M/Briz-M | Ekspress-80 & Ekspress-103,StatusActive,65.00,Success,2020,Kazakhstan,"[Baikonur, Cosmodrome]"
4,4,4,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA",2020-07-30 11:50:00+00:00,Atlas V 541 | Perseverance,StatusActive,145.00,Success,2020,USA,[Florida]
...,...,...,...,...,...,...,...,...,...,...,...,...
4319,4319,4319,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1958-02-05 07:33:00+00:00,Vanguard | Vanguard TV3BU,StatusRetired,NaN,Failure,1958,USA,[Florida]
4320,4320,4320,AMBA,"LC-26A, Cape Canaveral AFS, Florida, USA",1958-02-01 03:48:00+00:00,Juno I | Explorer 1,StatusRetired,NaN,Success,1958,USA,[Florida]
4321,4321,4321,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1957-12-06 16:44:00+00:00,Vanguard | Vanguard TV3,StatusRetired,NaN,Failure,1957,USA,[Florida]
4322,4322,4322,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-11-03 02:30:00+00:00,Sputnik 8K71PS | Sputnik-2,StatusRetired,NaN,Success,1957,Kazakhstan,"[Baikonur, Cosmodrome]"
4323,4323,4323,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-10-04 19:28:00+00:00,Sputnik 8K71PS | Sputnik-1,StatusRetired,NaN,Success,1957,Kazakhstan,"[Baikonur, Cosmodrome]"

In [185]:
df.drop(columns=['states/provinces'], inplace=True)

In [186]:
df

,Unnamed: 0.1,Unnamed: 0,Organisation,Location,Date,Detail,Rocket_Status,Price,Mission_Status,year,Country
0,0,0,SpaceX,"LC-39A, Kennedy Space Center, Florida, USA",2020-08-07 05:12:00+00:00,Falcon 9 Block 5 | Starlink V1 L9 & BlackSky,StatusActive,50.00,Success,2020,USA
1,1,1,CASC,"Site 9401 (SLS-2), Jiuquan Satellite Launch Ce...",2020-08-06 04:01:00+00:00,Long March 2D | Gaofen-9 04 & Q-SAT,StatusActive,29.75,Success,2020,China
2,2,2,SpaceX,"Pad A, Boca Chica, Texas, USA",2020-08-04 23:57:00+00:00,Starship Prototype | 150 Meter Hop,StatusActive,NaN,Success,2020,USA
3,3,3,Roscosmos,"Site 200/39, Baikonur Cosmodrome, Kazakhstan",2020-07-30 21:25:00+00:00,Proton-M/Briz-M | Ekspress-80 & Ekspress-103,StatusActive,65.00,Success,2020,Kazakhstan
4,4,4,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA",2020-07-30 11:50:00+00:00,Atlas V 541 | Perseverance,StatusActive,145.00,Success,2020,USA
...,...,...,...,...,...,...,...,...,...,...,...
4319,4319,4319,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1958-02-05 07:33:00+00:00,Vanguard | Vanguard TV3BU,StatusRetired,NaN,Failure,1958,USA
4320,4320,4320,AMBA,"LC-26A, Cape Canaveral AFS, Florida, USA",1958-02-01 03:48:00+00:00,Juno I | Explorer 1,StatusRetired,NaN,Success,1958,USA
4321,4321,4321,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",1957-12-06 16:44:00+00:00,Vanguard | Vanguard TV3,StatusRetired,NaN,Failure,1957,USA
4322,4322,4322,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-11-03 02:30:00+00:00,Sputnik 8K71PS | Sputnik-2,StatusRetired,NaN,Success,1957,Kazakhstan
4323,4323,4323,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",1957-10-04 19:28:00+00:00,Sputnik 8K71PS | Sputnik-1,StatusRetired,NaN,Success,1957,Kazakhstan

In [219]:
df_final_analysis = df.groupby('Organisation').agg({'Organisation':pd.Series.count})

In [220]:
df_final_analysis.columns = ['Total Missions']

In [221]:
success_Countcount = success_Count.groupby('Organisation').agg({'Organisation':pd.Series.count})
success_Countcount.columns = ['Successful Missions']
success_Countcount

                  Successful Missions
Organisation
AMBA                                4
ASI                                 9
Arianespace                       269
Arm??e de l'Air                     3
Blue Origin                        12
Boeing                            131
CASC                              231
CASIC                               3
CECLES                              1
CNES                                6
Douglas                             1
ESA                                 9
Eurockot                           12
ExPace                              9
General Dynamics                  203
IAI                                 9
ILS                                45
IRGC                                1
ISA                                 4
ISAS                               26
ISRO                               63
JAXA                                6
KARI                                1
KCST                                2
Khrunichev                          1
Kosmotras                          21
Land Launch                         6
Lockheed                           74
MHI                                80
MITT                                6
Martin Marietta                   100
NASA                              186
Northrop                           74
OKB-586                             2
RAE                                 1
RVSN USSR                        1614
Rocket Lab                         11
Roscosmos                          51
SRC                                 2
Sea Launch                         33
SpaceX                             94
Starsem                             1
ULA                               139
US Air Force                      129
US Navy                             2
UT                                  1
VKS RF                            188
Yuzhmash                            2
i-Space                             1

In [226]:
success_percentage = (success_Countcount['Successful Missions']/df_final_analysis['Total Missions'])*100
success_percentage = success_percentage.to_frame(name='Success Percentage')
success_percentage

                  Success Percentage
Organisation
AEB                              NaN
AMBA                       50.000000
ASI                       100.000000
Arianespace                96.415771
Arm??e de l'Air            75.000000
Blue Origin               100.000000
Boeing                     96.323529
CASC                       92.031873
CASIC                      60.000000
CECLES                     25.000000
CNES                       75.000000
Douglas                   100.000000
EER                              NaN
ESA                        69.230769
Eurockot                   92.307692
ExPace                     90.000000
Exos                             NaN
General Dynamics           80.876494
IAI                        81.818182
ILS                        97.826087
IRGC                      100.000000
ISA                        30.769231
ISAS                       86.666667
ISRO                       82.894737
JAXA                       85.714286
KARI                       33.333333
KCST                       40.000000
Khrunichev                100.000000
Kosmotras                  95.454545
Land Launch                85.714286
Landspace                        NaN
Lockheed                   93.670886
MHI                        95.238095
MITT                       85.714286
Martin Marietta            87.719298
NASA                       91.625616
Northrop                   89.156627
OKB-586                   100.000000
OneSpace                         NaN
RAE                        50.000000
RVSN USSR                  90.827237
Rocket Lab                 84.615385
Roscosmos                  92.727273
SRC                        66.666667
Sandia                           NaN
Sea Launch                 91.666667
SpaceX                     94.000000
Starsem                   100.000000
ULA                        99.285714
US Air Force               80.124224
US Navy                    11.764706
UT                         20.000000
VKS RF                     93.532338
Virgin Orbit                     NaN
Yuzhmash                  100.000000
i-Space                   100.000000

In [227]:
df_final_analysis_ = pd.merge(df_final_analysis, success_percentage, on='Organisation', how='left')
df_final_analysis_

                  Total Missions  Success Percentage
Organisation
AEB                            3                 NaN
AMBA                           8           50.000000
ASI                            9          100.000000
Arianespace                  279           96.415771
Arm??e de l'Air                4           75.000000
Blue Origin                   12          100.000000
Boeing                       136           96.323529
CASC                         251           92.031873
CASIC                          5           60.000000
CECLES                         4           25.000000
CNES                           8           75.000000
Douglas                        1          100.000000
EER                            1                 NaN
ESA                           13           69.230769
Eurockot                      13           92.307692
ExPace                        10           90.000000
Exos                           4                 NaN
General Dynamics             251           80.876494
IAI                           11           81.818182
ILS                           46           97.826087
IRGC                           1          100.000000
ISA                           13           30.769231
ISAS                          30           86.666667
ISRO                          76           82.894737
JAXA                           7           85.714286
KARI                           3           33.333333
KCST                           5           40.000000
Khrunichev                     1          100.000000
Kosmotras                     22           95.454545
Land Launch                    7           85.714286
Landspace                      1                 NaN
Lockheed                      79           93.670886
MHI                           84           95.238095
MITT                           7           85.714286
Martin Marietta              114           87.719298
NASA                         203           91.625616
Northrop                      83           89.156627
OKB-586                        2          100.000000
OneSpace                       1                 NaN
RAE                            2           50.000000
RVSN USSR                   1777           90.827237
Rocket Lab                    13           84.615385
Roscosmos                     55           92.727273
SRC                            3           66.666667
Sandia                         1                 NaN
Sea Launch                    36           91.666667
SpaceX                       100           94.000000
Starsem                        1          100.000000
ULA                          140           99.285714
US Air Force                 161           80.124224
US Navy                       17           11.764706
UT                             5           20.000000
VKS RF                       201           93.532338
Virgin Orbit                   1                 NaN
Yuzhmash                       2          100.000000
i-Space                        1          100.000000

In [228]:
df_final_analysis_['Success Percentage'] = df_final_analysis_.apply(lambda x:(x['Success Percentage']*0.5) if x['Total Missions'] < 50 else x['Success Percentage'], axis=1)

In [229]:
df_final_analysis_

                  Total Missions  Success Percentage
Organisation
AEB                            3                 NaN
AMBA                           8           25.000000
ASI                            9           50.000000
Arianespace                  279           96.415771
Arm??e de l'Air                4           37.500000
Blue Origin                   12           50.000000
Boeing                       136           96.323529
CASC                         251           92.031873
CASIC                          5           30.000000
CECLES                         4           12.500000
CNES                           8           37.500000
Douglas                        1           50.000000
EER                            1                 NaN
ESA                           13           34.615385
Eurockot                      13           46.153846
ExPace                        10           45.000000
Exos                           4                 NaN
General Dynamics             251           80.876494
IAI                           11           40.909091
ILS                           46           48.913043
IRGC                           1           50.000000
ISA                           13           15.384615
ISAS                          30           43.333333
ISRO                          76           82.894737
JAXA                           7           42.857143
KARI                           3           16.666667
KCST                           5           20.000000
Khrunichev                     1           50.000000
Kosmotras                     22           47.727273
Land Launch                    7           42.857143
Landspace                      1                 NaN
Lockheed                      79           93.670886
MHI                           84           95.238095
MITT                           7           42.857143
Martin Marietta              114           87.719298
NASA                         203           91.625616
Northrop                      83           89.156627
OKB-586                        2           50.000000
OneSpace                       1                 NaN
RAE                            2           25.000000
RVSN USSR                   1777           90.827237
Rocket Lab                    13           42.307692
Roscosmos                     55           92.727273
SRC                            3           33.333333
Sandia                         1                 NaN
Sea Launch                    36           45.833333
SpaceX                       100           94.000000
Starsem                        1           50.000000
ULA                          140           99.285714
US Air Force                 161           80.124224
US Navy                       17            5.882353
UT                             5           10.000000
VKS RF                       201           93.532338
Virgin Orbit                   1                 NaN
Yuzhmash                       2           50.000000
i-Space                        1           50.000000